package com.sunmw.paipai.domain;

import java.math.BigDecimal;
import java.util.Date;

public class PpOrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.pp_order_item_id
     *
     * @mbggenerated
     */
    private Integer ppOrderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.deal_sub_code
     *
     * @mbggenerated
     */
    private String dealSubCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_code
     *
     * @mbggenerated
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_code_history
     *
     * @mbggenerated
     */
    private String itemCodeHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_local_code
     *
     * @mbggenerated
     */
    private String itemLocalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.stock_local_code
     *
     * @mbggenerated
     */
    private String stockLocalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.stock_attr
     *
     * @mbggenerated
     */
    private String stockAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_detail_link
     *
     * @mbggenerated
     */
    private String itemDetailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_pic80
     *
     * @mbggenerated
     */
    private String itemPic80;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_retail_price
     *
     * @mbggenerated
     */
    private BigDecimal itemRetailPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_deal_price
     *
     * @mbggenerated
     */
    private BigDecimal itemDealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_adjust_price
     *
     * @mbggenerated
     */
    private BigDecimal itemAdjustPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_discount_fee
     *
     * @mbggenerated
     */
    private BigDecimal itemDiscountFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_deal_count
     *
     * @mbggenerated
     */
    private Integer itemDealCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.item_flag
     *
     * @mbggenerated
     */
    private String itemFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.refund_state
     *
     * @mbggenerated
     */
    private String refundState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.refund_state_desc
     *
     * @mbggenerated
     */
    private String refundStateDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.trade_property_mask
     *
     * @mbggenerated
     */
    private String tradePropertyMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.available_action
     *
     * @mbggenerated
     */
    private String availableAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.deal_code
     *
     * @mbggenerated
     */
    private String dealCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_item.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.pp_order_item_id
     *
     * @return the value of pp_order_item.pp_order_item_id
     *
     * @mbggenerated
     */
    public Integer getPpOrderItemId() {
        return ppOrderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.pp_order_item_id
     *
     * @param ppOrderItemId the value for pp_order_item.pp_order_item_id
     *
     * @mbggenerated
     */
    public void setPpOrderItemId(Integer ppOrderItemId) {
        this.ppOrderItemId = ppOrderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.deal_sub_code
     *
     * @return the value of pp_order_item.deal_sub_code
     *
     * @mbggenerated
     */
    public String getDealSubCode() {
        return dealSubCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.deal_sub_code
     *
     * @param dealSubCode the value for pp_order_item.deal_sub_code
     *
     * @mbggenerated
     */
    public void setDealSubCode(String dealSubCode) {
        this.dealSubCode = dealSubCode == null ? null : dealSubCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_code
     *
     * @return the value of pp_order_item.item_code
     *
     * @mbggenerated
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_code
     *
     * @param itemCode the value for pp_order_item.item_code
     *
     * @mbggenerated
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_code_history
     *
     * @return the value of pp_order_item.item_code_history
     *
     * @mbggenerated
     */
    public String getItemCodeHistory() {
        return itemCodeHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_code_history
     *
     * @param itemCodeHistory the value for pp_order_item.item_code_history
     *
     * @mbggenerated
     */
    public void setItemCodeHistory(String itemCodeHistory) {
        this.itemCodeHistory = itemCodeHistory == null ? null : itemCodeHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_local_code
     *
     * @return the value of pp_order_item.item_local_code
     *
     * @mbggenerated
     */
    public String getItemLocalCode() {
        return itemLocalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_local_code
     *
     * @param itemLocalCode the value for pp_order_item.item_local_code
     *
     * @mbggenerated
     */
    public void setItemLocalCode(String itemLocalCode) {
        this.itemLocalCode = itemLocalCode == null ? null : itemLocalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.stock_local_code
     *
     * @return the value of pp_order_item.stock_local_code
     *
     * @mbggenerated
     */
    public String getStockLocalCode() {
        return stockLocalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.stock_local_code
     *
     * @param stockLocalCode the value for pp_order_item.stock_local_code
     *
     * @mbggenerated
     */
    public void setStockLocalCode(String stockLocalCode) {
        this.stockLocalCode = stockLocalCode == null ? null : stockLocalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.stock_attr
     *
     * @return the value of pp_order_item.stock_attr
     *
     * @mbggenerated
     */
    public String getStockAttr() {
        return stockAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.stock_attr
     *
     * @param stockAttr the value for pp_order_item.stock_attr
     *
     * @mbggenerated
     */
    public void setStockAttr(String stockAttr) {
        this.stockAttr = stockAttr == null ? null : stockAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_detail_link
     *
     * @return the value of pp_order_item.item_detail_link
     *
     * @mbggenerated
     */
    public String getItemDetailLink() {
        return itemDetailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_detail_link
     *
     * @param itemDetailLink the value for pp_order_item.item_detail_link
     *
     * @mbggenerated
     */
    public void setItemDetailLink(String itemDetailLink) {
        this.itemDetailLink = itemDetailLink == null ? null : itemDetailLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_name
     *
     * @return the value of pp_order_item.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_name
     *
     * @param itemName the value for pp_order_item.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_pic80
     *
     * @return the value of pp_order_item.item_pic80
     *
     * @mbggenerated
     */
    public String getItemPic80() {
        return itemPic80;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_pic80
     *
     * @param itemPic80 the value for pp_order_item.item_pic80
     *
     * @mbggenerated
     */
    public void setItemPic80(String itemPic80) {
        this.itemPic80 = itemPic80 == null ? null : itemPic80.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_retail_price
     *
     * @return the value of pp_order_item.item_retail_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemRetailPrice() {
        return itemRetailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_retail_price
     *
     * @param itemRetailPrice the value for pp_order_item.item_retail_price
     *
     * @mbggenerated
     */
    public void setItemRetailPrice(BigDecimal itemRetailPrice) {
        this.itemRetailPrice = itemRetailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_deal_price
     *
     * @return the value of pp_order_item.item_deal_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemDealPrice() {
        return itemDealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_deal_price
     *
     * @param itemDealPrice the value for pp_order_item.item_deal_price
     *
     * @mbggenerated
     */
    public void setItemDealPrice(BigDecimal itemDealPrice) {
        this.itemDealPrice = itemDealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_adjust_price
     *
     * @return the value of pp_order_item.item_adjust_price
     *
     * @mbggenerated
     */
    public BigDecimal getItemAdjustPrice() {
        return itemAdjustPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_adjust_price
     *
     * @param itemAdjustPrice the value for pp_order_item.item_adjust_price
     *
     * @mbggenerated
     */
    public void setItemAdjustPrice(BigDecimal itemAdjustPrice) {
        this.itemAdjustPrice = itemAdjustPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_discount_fee
     *
     * @return the value of pp_order_item.item_discount_fee
     *
     * @mbggenerated
     */
    public BigDecimal getItemDiscountFee() {
        return itemDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_discount_fee
     *
     * @param itemDiscountFee the value for pp_order_item.item_discount_fee
     *
     * @mbggenerated
     */
    public void setItemDiscountFee(BigDecimal itemDiscountFee) {
        this.itemDiscountFee = itemDiscountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_deal_count
     *
     * @return the value of pp_order_item.item_deal_count
     *
     * @mbggenerated
     */
    public Integer getItemDealCount() {
        return itemDealCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_deal_count
     *
     * @param itemDealCount the value for pp_order_item.item_deal_count
     *
     * @mbggenerated
     */
    public void setItemDealCount(Integer itemDealCount) {
        this.itemDealCount = itemDealCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.account
     *
     * @return the value of pp_order_item.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.account
     *
     * @param account the value for pp_order_item.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.item_flag
     *
     * @return the value of pp_order_item.item_flag
     *
     * @mbggenerated
     */
    public String getItemFlag() {
        return itemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.item_flag
     *
     * @param itemFlag the value for pp_order_item.item_flag
     *
     * @mbggenerated
     */
    public void setItemFlag(String itemFlag) {
        this.itemFlag = itemFlag == null ? null : itemFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.refund_state
     *
     * @return the value of pp_order_item.refund_state
     *
     * @mbggenerated
     */
    public String getRefundState() {
        return refundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.refund_state
     *
     * @param refundState the value for pp_order_item.refund_state
     *
     * @mbggenerated
     */
    public void setRefundState(String refundState) {
        this.refundState = refundState == null ? null : refundState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.refund_state_desc
     *
     * @return the value of pp_order_item.refund_state_desc
     *
     * @mbggenerated
     */
    public String getRefundStateDesc() {
        return refundStateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.refund_state_desc
     *
     * @param refundStateDesc the value for pp_order_item.refund_state_desc
     *
     * @mbggenerated
     */
    public void setRefundStateDesc(String refundStateDesc) {
        this.refundStateDesc = refundStateDesc == null ? null : refundStateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.trade_property_mask
     *
     * @return the value of pp_order_item.trade_property_mask
     *
     * @mbggenerated
     */
    public String getTradePropertyMask() {
        return tradePropertyMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.trade_property_mask
     *
     * @param tradePropertyMask the value for pp_order_item.trade_property_mask
     *
     * @mbggenerated
     */
    public void setTradePropertyMask(String tradePropertyMask) {
        this.tradePropertyMask = tradePropertyMask == null ? null : tradePropertyMask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.available_action
     *
     * @return the value of pp_order_item.available_action
     *
     * @mbggenerated
     */
    public String getAvailableAction() {
        return availableAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.available_action
     *
     * @param availableAction the value for pp_order_item.available_action
     *
     * @mbggenerated
     */
    public void setAvailableAction(String availableAction) {
        this.availableAction = availableAction == null ? null : availableAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.deal_code
     *
     * @return the value of pp_order_item.deal_code
     *
     * @mbggenerated
     */
    public String getDealCode() {
        return dealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.deal_code
     *
     * @param dealCode the value for pp_order_item.deal_code
     *
     * @mbggenerated
     */
    public void setDealCode(String dealCode) {
        this.dealCode = dealCode == null ? null : dealCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.store_id
     *
     * @return the value of pp_order_item.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.store_id
     *
     * @param storeId the value for pp_order_item.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.update_time
     *
     * @return the value of pp_order_item.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.update_time
     *
     * @param updateTime the value for pp_order_item.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_item.update_flag
     *
     * @return the value of pp_order_item.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_item.update_flag
     *
     * @param updateFlag the value for pp_order_item.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }
}