package com.sunmw.paipai.domain;

import java.math.BigDecimal;
import java.util.Date;

public class PpOrderHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.pp_order_head_id
     *
     * @mbggenerated
     */
    private Integer ppOrderHeadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.seller_crm
     *
     * @mbggenerated
     */
    private String sellerCrm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.buyer_name
     *
     * @mbggenerated
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.buyer_uin
     *
     * @mbggenerated
     */
    private String buyerUin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.buyer_remark
     *
     * @mbggenerated
     */
    private String buyerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.combo_info
     *
     * @mbggenerated
     */
    private String comboInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_code
     *
     * @mbggenerated
     */
    private String dealCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_desc
     *
     * @mbggenerated
     */
    private String dealDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_detail_link
     *
     * @mbggenerated
     */
    private String dealDetailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_note_type
     *
     * @mbggenerated
     */
    private String dealNoteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_note
     *
     * @mbggenerated
     */
    private String dealNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_state
     *
     * @mbggenerated
     */
    private String dealState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_state_desc
     *
     * @mbggenerated
     */
    private String dealStateDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.property_mask
     *
     * @mbggenerated
     */
    private String propertyMask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_type
     *
     * @mbggenerated
     */
    private String dealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_type_desc
     *
     * @mbggenerated
     */
    private String dealTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_pay_type
     *
     * @mbggenerated
     */
    private String dealPayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_pay_type_desc
     *
     * @mbggenerated
     */
    private String dealPayTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_rate_state
     *
     * @mbggenerated
     */
    private String dealRateState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_rate_state_desc
     *
     * @mbggenerated
     */
    private String dealRateStateDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_end_time
     *
     * @mbggenerated
     */
    private Date dealEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.pay_return_time
     *
     * @mbggenerated
     */
    private Date payReturnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.recvfee_return_time
     *
     * @mbggenerated
     */
    private Date recvfeeReturnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.recvfee_time
     *
     * @mbggenerated
     */
    private Date recvfeeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.seller_consignment_time
     *
     * @mbggenerated
     */
    private Date sellerConsignmentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.has_invoice
     *
     * @mbggenerated
     */
    private Integer hasInvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.invoice_content
     *
     * @mbggenerated
     */
    private String invoiceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.invoice_title
     *
     * @mbggenerated
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.tenpay_code
     *
     * @mbggenerated
     */
    private String tenpayCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.transport_type
     *
     * @mbggenerated
     */
    private String transportType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.transport_type_desc
     *
     * @mbggenerated
     */
    private String transportTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.who_pay_shippingfee
     *
     * @mbggenerated
     */
    private Integer whoPayShippingfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.wuliu_id
     *
     * @mbggenerated
     */
    private String wuliuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.receiver_address
     *
     * @mbggenerated
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.receiver_mobile
     *
     * @mbggenerated
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.receiver_phone
     *
     * @mbggenerated
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.receiver_postcode
     *
     * @mbggenerated
     */
    private String receiverPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.seller_recv_refund
     *
     * @mbggenerated
     */
    private BigDecimal sellerRecvRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.buyer_recv_refund
     *
     * @mbggenerated
     */
    private BigDecimal buyerRecvRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.coupon_fee
     *
     * @mbggenerated
     */
    private BigDecimal couponFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_pay_fee_point
     *
     * @mbggenerated
     */
    private Long dealPayFeePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_pay_fee_ticket
     *
     * @mbggenerated
     */
    private BigDecimal dealPayFeeTicket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.deal_pay_fee_total
     *
     * @mbggenerated
     */
    private BigDecimal dealPayFeeTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.freight
     *
     * @mbggenerated
     */
    private BigDecimal freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.shippingfee_calc
     *
     * @mbggenerated
     */
    private BigDecimal shippingfeeCalc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.total_cash
     *
     * @mbggenerated
     */
    private BigDecimal totalCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.seller_name
     *
     * @mbggenerated
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.seller_uin
     *
     * @mbggenerated
     */
    private String sellerUin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.expect_arrival_time
     *
     * @mbggenerated
     */
    private Date expectArrivalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pp_order_head.update_flag
     *
     * @mbggenerated
     */
    private String updateFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.pp_order_head_id
     *
     * @return the value of pp_order_head.pp_order_head_id
     *
     * @mbggenerated
     */
    public Integer getPpOrderHeadId() {
        return ppOrderHeadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.pp_order_head_id
     *
     * @param ppOrderHeadId the value for pp_order_head.pp_order_head_id
     *
     * @mbggenerated
     */
    public void setPpOrderHeadId(Integer ppOrderHeadId) {
        this.ppOrderHeadId = ppOrderHeadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.seller_crm
     *
     * @return the value of pp_order_head.seller_crm
     *
     * @mbggenerated
     */
    public String getSellerCrm() {
        return sellerCrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.seller_crm
     *
     * @param sellerCrm the value for pp_order_head.seller_crm
     *
     * @mbggenerated
     */
    public void setSellerCrm(String sellerCrm) {
        this.sellerCrm = sellerCrm == null ? null : sellerCrm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.buyer_name
     *
     * @return the value of pp_order_head.buyer_name
     *
     * @mbggenerated
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.buyer_name
     *
     * @param buyerName the value for pp_order_head.buyer_name
     *
     * @mbggenerated
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.buyer_uin
     *
     * @return the value of pp_order_head.buyer_uin
     *
     * @mbggenerated
     */
    public String getBuyerUin() {
        return buyerUin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.buyer_uin
     *
     * @param buyerUin the value for pp_order_head.buyer_uin
     *
     * @mbggenerated
     */
    public void setBuyerUin(String buyerUin) {
        this.buyerUin = buyerUin == null ? null : buyerUin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.buyer_remark
     *
     * @return the value of pp_order_head.buyer_remark
     *
     * @mbggenerated
     */
    public String getBuyerRemark() {
        return buyerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.buyer_remark
     *
     * @param buyerRemark the value for pp_order_head.buyer_remark
     *
     * @mbggenerated
     */
    public void setBuyerRemark(String buyerRemark) {
        this.buyerRemark = buyerRemark == null ? null : buyerRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.combo_info
     *
     * @return the value of pp_order_head.combo_info
     *
     * @mbggenerated
     */
    public String getComboInfo() {
        return comboInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.combo_info
     *
     * @param comboInfo the value for pp_order_head.combo_info
     *
     * @mbggenerated
     */
    public void setComboInfo(String comboInfo) {
        this.comboInfo = comboInfo == null ? null : comboInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_code
     *
     * @return the value of pp_order_head.deal_code
     *
     * @mbggenerated
     */
    public String getDealCode() {
        return dealCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_code
     *
     * @param dealCode the value for pp_order_head.deal_code
     *
     * @mbggenerated
     */
    public void setDealCode(String dealCode) {
        this.dealCode = dealCode == null ? null : dealCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_desc
     *
     * @return the value of pp_order_head.deal_desc
     *
     * @mbggenerated
     */
    public String getDealDesc() {
        return dealDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_desc
     *
     * @param dealDesc the value for pp_order_head.deal_desc
     *
     * @mbggenerated
     */
    public void setDealDesc(String dealDesc) {
        this.dealDesc = dealDesc == null ? null : dealDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_detail_link
     *
     * @return the value of pp_order_head.deal_detail_link
     *
     * @mbggenerated
     */
    public String getDealDetailLink() {
        return dealDetailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_detail_link
     *
     * @param dealDetailLink the value for pp_order_head.deal_detail_link
     *
     * @mbggenerated
     */
    public void setDealDetailLink(String dealDetailLink) {
        this.dealDetailLink = dealDetailLink == null ? null : dealDetailLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_note_type
     *
     * @return the value of pp_order_head.deal_note_type
     *
     * @mbggenerated
     */
    public String getDealNoteType() {
        return dealNoteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_note_type
     *
     * @param dealNoteType the value for pp_order_head.deal_note_type
     *
     * @mbggenerated
     */
    public void setDealNoteType(String dealNoteType) {
        this.dealNoteType = dealNoteType == null ? null : dealNoteType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_note
     *
     * @return the value of pp_order_head.deal_note
     *
     * @mbggenerated
     */
    public String getDealNote() {
        return dealNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_note
     *
     * @param dealNote the value for pp_order_head.deal_note
     *
     * @mbggenerated
     */
    public void setDealNote(String dealNote) {
        this.dealNote = dealNote == null ? null : dealNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_state
     *
     * @return the value of pp_order_head.deal_state
     *
     * @mbggenerated
     */
    public String getDealState() {
        return dealState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_state
     *
     * @param dealState the value for pp_order_head.deal_state
     *
     * @mbggenerated
     */
    public void setDealState(String dealState) {
        this.dealState = dealState == null ? null : dealState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_state_desc
     *
     * @return the value of pp_order_head.deal_state_desc
     *
     * @mbggenerated
     */
    public String getDealStateDesc() {
        return dealStateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_state_desc
     *
     * @param dealStateDesc the value for pp_order_head.deal_state_desc
     *
     * @mbggenerated
     */
    public void setDealStateDesc(String dealStateDesc) {
        this.dealStateDesc = dealStateDesc == null ? null : dealStateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.property_mask
     *
     * @return the value of pp_order_head.property_mask
     *
     * @mbggenerated
     */
    public String getPropertyMask() {
        return propertyMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.property_mask
     *
     * @param propertyMask the value for pp_order_head.property_mask
     *
     * @mbggenerated
     */
    public void setPropertyMask(String propertyMask) {
        this.propertyMask = propertyMask == null ? null : propertyMask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_type
     *
     * @return the value of pp_order_head.deal_type
     *
     * @mbggenerated
     */
    public String getDealType() {
        return dealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_type
     *
     * @param dealType the value for pp_order_head.deal_type
     *
     * @mbggenerated
     */
    public void setDealType(String dealType) {
        this.dealType = dealType == null ? null : dealType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_type_desc
     *
     * @return the value of pp_order_head.deal_type_desc
     *
     * @mbggenerated
     */
    public String getDealTypeDesc() {
        return dealTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_type_desc
     *
     * @param dealTypeDesc the value for pp_order_head.deal_type_desc
     *
     * @mbggenerated
     */
    public void setDealTypeDesc(String dealTypeDesc) {
        this.dealTypeDesc = dealTypeDesc == null ? null : dealTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_pay_type
     *
     * @return the value of pp_order_head.deal_pay_type
     *
     * @mbggenerated
     */
    public String getDealPayType() {
        return dealPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_pay_type
     *
     * @param dealPayType the value for pp_order_head.deal_pay_type
     *
     * @mbggenerated
     */
    public void setDealPayType(String dealPayType) {
        this.dealPayType = dealPayType == null ? null : dealPayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_pay_type_desc
     *
     * @return the value of pp_order_head.deal_pay_type_desc
     *
     * @mbggenerated
     */
    public String getDealPayTypeDesc() {
        return dealPayTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_pay_type_desc
     *
     * @param dealPayTypeDesc the value for pp_order_head.deal_pay_type_desc
     *
     * @mbggenerated
     */
    public void setDealPayTypeDesc(String dealPayTypeDesc) {
        this.dealPayTypeDesc = dealPayTypeDesc == null ? null : dealPayTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_rate_state
     *
     * @return the value of pp_order_head.deal_rate_state
     *
     * @mbggenerated
     */
    public String getDealRateState() {
        return dealRateState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_rate_state
     *
     * @param dealRateState the value for pp_order_head.deal_rate_state
     *
     * @mbggenerated
     */
    public void setDealRateState(String dealRateState) {
        this.dealRateState = dealRateState == null ? null : dealRateState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_rate_state_desc
     *
     * @return the value of pp_order_head.deal_rate_state_desc
     *
     * @mbggenerated
     */
    public String getDealRateStateDesc() {
        return dealRateStateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_rate_state_desc
     *
     * @param dealRateStateDesc the value for pp_order_head.deal_rate_state_desc
     *
     * @mbggenerated
     */
    public void setDealRateStateDesc(String dealRateStateDesc) {
        this.dealRateStateDesc = dealRateStateDesc == null ? null : dealRateStateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.create_time
     *
     * @return the value of pp_order_head.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.create_time
     *
     * @param createTime the value for pp_order_head.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_end_time
     *
     * @return the value of pp_order_head.deal_end_time
     *
     * @mbggenerated
     */
    public Date getDealEndTime() {
        return dealEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_end_time
     *
     * @param dealEndTime the value for pp_order_head.deal_end_time
     *
     * @mbggenerated
     */
    public void setDealEndTime(Date dealEndTime) {
        this.dealEndTime = dealEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.last_update_time
     *
     * @return the value of pp_order_head.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.last_update_time
     *
     * @param lastUpdateTime the value for pp_order_head.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.pay_time
     *
     * @return the value of pp_order_head.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.pay_time
     *
     * @param payTime the value for pp_order_head.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.pay_return_time
     *
     * @return the value of pp_order_head.pay_return_time
     *
     * @mbggenerated
     */
    public Date getPayReturnTime() {
        return payReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.pay_return_time
     *
     * @param payReturnTime the value for pp_order_head.pay_return_time
     *
     * @mbggenerated
     */
    public void setPayReturnTime(Date payReturnTime) {
        this.payReturnTime = payReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.recvfee_return_time
     *
     * @return the value of pp_order_head.recvfee_return_time
     *
     * @mbggenerated
     */
    public Date getRecvfeeReturnTime() {
        return recvfeeReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.recvfee_return_time
     *
     * @param recvfeeReturnTime the value for pp_order_head.recvfee_return_time
     *
     * @mbggenerated
     */
    public void setRecvfeeReturnTime(Date recvfeeReturnTime) {
        this.recvfeeReturnTime = recvfeeReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.recvfee_time
     *
     * @return the value of pp_order_head.recvfee_time
     *
     * @mbggenerated
     */
    public Date getRecvfeeTime() {
        return recvfeeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.recvfee_time
     *
     * @param recvfeeTime the value for pp_order_head.recvfee_time
     *
     * @mbggenerated
     */
    public void setRecvfeeTime(Date recvfeeTime) {
        this.recvfeeTime = recvfeeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.seller_consignment_time
     *
     * @return the value of pp_order_head.seller_consignment_time
     *
     * @mbggenerated
     */
    public Date getSellerConsignmentTime() {
        return sellerConsignmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.seller_consignment_time
     *
     * @param sellerConsignmentTime the value for pp_order_head.seller_consignment_time
     *
     * @mbggenerated
     */
    public void setSellerConsignmentTime(Date sellerConsignmentTime) {
        this.sellerConsignmentTime = sellerConsignmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.has_invoice
     *
     * @return the value of pp_order_head.has_invoice
     *
     * @mbggenerated
     */
    public Integer getHasInvoice() {
        return hasInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.has_invoice
     *
     * @param hasInvoice the value for pp_order_head.has_invoice
     *
     * @mbggenerated
     */
    public void setHasInvoice(Integer hasInvoice) {
        this.hasInvoice = hasInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.invoice_content
     *
     * @return the value of pp_order_head.invoice_content
     *
     * @mbggenerated
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.invoice_content
     *
     * @param invoiceContent the value for pp_order_head.invoice_content
     *
     * @mbggenerated
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.invoice_title
     *
     * @return the value of pp_order_head.invoice_title
     *
     * @mbggenerated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.invoice_title
     *
     * @param invoiceTitle the value for pp_order_head.invoice_title
     *
     * @mbggenerated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.tenpay_code
     *
     * @return the value of pp_order_head.tenpay_code
     *
     * @mbggenerated
     */
    public String getTenpayCode() {
        return tenpayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.tenpay_code
     *
     * @param tenpayCode the value for pp_order_head.tenpay_code
     *
     * @mbggenerated
     */
    public void setTenpayCode(String tenpayCode) {
        this.tenpayCode = tenpayCode == null ? null : tenpayCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.transport_type
     *
     * @return the value of pp_order_head.transport_type
     *
     * @mbggenerated
     */
    public String getTransportType() {
        return transportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.transport_type
     *
     * @param transportType the value for pp_order_head.transport_type
     *
     * @mbggenerated
     */
    public void setTransportType(String transportType) {
        this.transportType = transportType == null ? null : transportType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.transport_type_desc
     *
     * @return the value of pp_order_head.transport_type_desc
     *
     * @mbggenerated
     */
    public String getTransportTypeDesc() {
        return transportTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.transport_type_desc
     *
     * @param transportTypeDesc the value for pp_order_head.transport_type_desc
     *
     * @mbggenerated
     */
    public void setTransportTypeDesc(String transportTypeDesc) {
        this.transportTypeDesc = transportTypeDesc == null ? null : transportTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.who_pay_shippingfee
     *
     * @return the value of pp_order_head.who_pay_shippingfee
     *
     * @mbggenerated
     */
    public Integer getWhoPayShippingfee() {
        return whoPayShippingfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.who_pay_shippingfee
     *
     * @param whoPayShippingfee the value for pp_order_head.who_pay_shippingfee
     *
     * @mbggenerated
     */
    public void setWhoPayShippingfee(Integer whoPayShippingfee) {
        this.whoPayShippingfee = whoPayShippingfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.wuliu_id
     *
     * @return the value of pp_order_head.wuliu_id
     *
     * @mbggenerated
     */
    public String getWuliuId() {
        return wuliuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.wuliu_id
     *
     * @param wuliuId the value for pp_order_head.wuliu_id
     *
     * @mbggenerated
     */
    public void setWuliuId(String wuliuId) {
        this.wuliuId = wuliuId == null ? null : wuliuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.receiver_address
     *
     * @return the value of pp_order_head.receiver_address
     *
     * @mbggenerated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.receiver_address
     *
     * @param receiverAddress the value for pp_order_head.receiver_address
     *
     * @mbggenerated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.receiver_mobile
     *
     * @return the value of pp_order_head.receiver_mobile
     *
     * @mbggenerated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.receiver_mobile
     *
     * @param receiverMobile the value for pp_order_head.receiver_mobile
     *
     * @mbggenerated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.receiver_name
     *
     * @return the value of pp_order_head.receiver_name
     *
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.receiver_name
     *
     * @param receiverName the value for pp_order_head.receiver_name
     *
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.receiver_phone
     *
     * @return the value of pp_order_head.receiver_phone
     *
     * @mbggenerated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.receiver_phone
     *
     * @param receiverPhone the value for pp_order_head.receiver_phone
     *
     * @mbggenerated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.receiver_postcode
     *
     * @return the value of pp_order_head.receiver_postcode
     *
     * @mbggenerated
     */
    public String getReceiverPostcode() {
        return receiverPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.receiver_postcode
     *
     * @param receiverPostcode the value for pp_order_head.receiver_postcode
     *
     * @mbggenerated
     */
    public void setReceiverPostcode(String receiverPostcode) {
        this.receiverPostcode = receiverPostcode == null ? null : receiverPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.seller_recv_refund
     *
     * @return the value of pp_order_head.seller_recv_refund
     *
     * @mbggenerated
     */
    public BigDecimal getSellerRecvRefund() {
        return sellerRecvRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.seller_recv_refund
     *
     * @param sellerRecvRefund the value for pp_order_head.seller_recv_refund
     *
     * @mbggenerated
     */
    public void setSellerRecvRefund(BigDecimal sellerRecvRefund) {
        this.sellerRecvRefund = sellerRecvRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.buyer_recv_refund
     *
     * @return the value of pp_order_head.buyer_recv_refund
     *
     * @mbggenerated
     */
    public BigDecimal getBuyerRecvRefund() {
        return buyerRecvRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.buyer_recv_refund
     *
     * @param buyerRecvRefund the value for pp_order_head.buyer_recv_refund
     *
     * @mbggenerated
     */
    public void setBuyerRecvRefund(BigDecimal buyerRecvRefund) {
        this.buyerRecvRefund = buyerRecvRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.coupon_fee
     *
     * @return the value of pp_order_head.coupon_fee
     *
     * @mbggenerated
     */
    public BigDecimal getCouponFee() {
        return couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.coupon_fee
     *
     * @param couponFee the value for pp_order_head.coupon_fee
     *
     * @mbggenerated
     */
    public void setCouponFee(BigDecimal couponFee) {
        this.couponFee = couponFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_pay_fee_point
     *
     * @return the value of pp_order_head.deal_pay_fee_point
     *
     * @mbggenerated
     */
    public Long getDealPayFeePoint() {
        return dealPayFeePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_pay_fee_point
     *
     * @param dealPayFeePoint the value for pp_order_head.deal_pay_fee_point
     *
     * @mbggenerated
     */
    public void setDealPayFeePoint(Long dealPayFeePoint) {
        this.dealPayFeePoint = dealPayFeePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_pay_fee_ticket
     *
     * @return the value of pp_order_head.deal_pay_fee_ticket
     *
     * @mbggenerated
     */
    public BigDecimal getDealPayFeeTicket() {
        return dealPayFeeTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_pay_fee_ticket
     *
     * @param dealPayFeeTicket the value for pp_order_head.deal_pay_fee_ticket
     *
     * @mbggenerated
     */
    public void setDealPayFeeTicket(BigDecimal dealPayFeeTicket) {
        this.dealPayFeeTicket = dealPayFeeTicket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.deal_pay_fee_total
     *
     * @return the value of pp_order_head.deal_pay_fee_total
     *
     * @mbggenerated
     */
    public BigDecimal getDealPayFeeTotal() {
        return dealPayFeeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.deal_pay_fee_total
     *
     * @param dealPayFeeTotal the value for pp_order_head.deal_pay_fee_total
     *
     * @mbggenerated
     */
    public void setDealPayFeeTotal(BigDecimal dealPayFeeTotal) {
        this.dealPayFeeTotal = dealPayFeeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.freight
     *
     * @return the value of pp_order_head.freight
     *
     * @mbggenerated
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.freight
     *
     * @param freight the value for pp_order_head.freight
     *
     * @mbggenerated
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.shippingfee_calc
     *
     * @return the value of pp_order_head.shippingfee_calc
     *
     * @mbggenerated
     */
    public BigDecimal getShippingfeeCalc() {
        return shippingfeeCalc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.shippingfee_calc
     *
     * @param shippingfeeCalc the value for pp_order_head.shippingfee_calc
     *
     * @mbggenerated
     */
    public void setShippingfeeCalc(BigDecimal shippingfeeCalc) {
        this.shippingfeeCalc = shippingfeeCalc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.total_cash
     *
     * @return the value of pp_order_head.total_cash
     *
     * @mbggenerated
     */
    public BigDecimal getTotalCash() {
        return totalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.total_cash
     *
     * @param totalCash the value for pp_order_head.total_cash
     *
     * @mbggenerated
     */
    public void setTotalCash(BigDecimal totalCash) {
        this.totalCash = totalCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.seller_name
     *
     * @return the value of pp_order_head.seller_name
     *
     * @mbggenerated
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.seller_name
     *
     * @param sellerName the value for pp_order_head.seller_name
     *
     * @mbggenerated
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.seller_uin
     *
     * @return the value of pp_order_head.seller_uin
     *
     * @mbggenerated
     */
    public String getSellerUin() {
        return sellerUin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.seller_uin
     *
     * @param sellerUin the value for pp_order_head.seller_uin
     *
     * @mbggenerated
     */
    public void setSellerUin(String sellerUin) {
        this.sellerUin = sellerUin == null ? null : sellerUin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.expect_arrival_time
     *
     * @return the value of pp_order_head.expect_arrival_time
     *
     * @mbggenerated
     */
    public Date getExpectArrivalTime() {
        return expectArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.expect_arrival_time
     *
     * @param expectArrivalTime the value for pp_order_head.expect_arrival_time
     *
     * @mbggenerated
     */
    public void setExpectArrivalTime(Date expectArrivalTime) {
        this.expectArrivalTime = expectArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.store_id
     *
     * @return the value of pp_order_head.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.store_id
     *
     * @param storeId the value for pp_order_head.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.update_time
     *
     * @return the value of pp_order_head.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.update_time
     *
     * @param updateTime the value for pp_order_head.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pp_order_head.update_flag
     *
     * @return the value of pp_order_head.update_flag
     *
     * @mbggenerated
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pp_order_head.update_flag
     *
     * @param updateFlag the value for pp_order_head.update_flag
     *
     * @mbggenerated
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag == null ? null : updateFlag.trim();
    }
}