package com.sunmw.web.dao.report;

import com.sunmw.web.domain.report.AlipayFinancialDetail;
import com.sunmw.web.domain.report.AlipayFinancialDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlipayFinancialDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int countByExample(AlipayFinancialDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int deleteByExample(AlipayFinancialDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int insert(AlipayFinancialDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int insertSelective(AlipayFinancialDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    List<AlipayFinancialDetail> selectByExample(AlipayFinancialDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    AlipayFinancialDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AlipayFinancialDetail record, @Param("example") AlipayFinancialDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AlipayFinancialDetail record, @Param("example") AlipayFinancialDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlipayFinancialDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_financial_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlipayFinancialDetail record);
}