package com.sunmw.web.dao.report;

import com.sunmw.web.domain.report.TaobaoAccountOther;
import com.sunmw.web.domain.report.TaobaoAccountOtherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaobaoAccountOtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int countByExample(TaobaoAccountOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int deleteByExample(TaobaoAccountOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int insert(TaobaoAccountOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int insertSelective(TaobaoAccountOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    List<TaobaoAccountOther> selectByExample(TaobaoAccountOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    TaobaoAccountOther selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaobaoAccountOther record, @Param("example") TaobaoAccountOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaobaoAccountOther record, @Param("example") TaobaoAccountOtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaobaoAccountOther record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_other
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaobaoAccountOther record);
}