package com.sunmw.web.dao;

import com.sunmw.web.domain.TaskDefine;
import com.sunmw.web.domain.TaskDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int countByExample(TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int deleteByExample(TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int insert(TaskDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int insertSelective(TaskDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    List<TaskDefine> selectByExample(TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    TaskDefine selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskDefine record, @Param("example") TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskDefine record, @Param("example") TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskDefine record);
}