package com.sunmw.web.domain;

import java.util.Date;

public class IfDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.IF_id
     *
     * @mbggenerated
     */
    private Long ifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.IF_code
     *
     * @mbggenerated
     */
    private String ifCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.IF_name
     *
     * @mbggenerated
     */
    private String ifName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.Error_retry_times
     *
     * @mbggenerated
     */
    private Integer errorRetryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.Retry_wait_seconds
     *
     * @mbggenerated
     */
    private Integer retryWaitSeconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.Run_method
     *
     * @mbggenerated
     */
    private String runMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.Class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.If_type
     *
     * @mbggenerated
     */
    private String ifType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.Class_type
     *
     * @mbggenerated
     */
    private String classType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.cuser
     *
     * @mbggenerated
     */
    private String cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.muser
     *
     * @mbggenerated
     */
    private String muser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column if_define.if_cat
     *
     * @mbggenerated
     */
    private String ifCat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.IF_id
     *
     * @return the value of if_define.IF_id
     *
     * @mbggenerated
     */
    public Long getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.IF_id
     *
     * @param ifId the value for if_define.IF_id
     *
     * @mbggenerated
     */
    public void setIfId(Long ifId) {
        this.ifId = ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.IF_code
     *
     * @return the value of if_define.IF_code
     *
     * @mbggenerated
     */
    public String getIfCode() {
        return ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.IF_code
     *
     * @param ifCode the value for if_define.IF_code
     *
     * @mbggenerated
     */
    public void setIfCode(String ifCode) {
        this.ifCode = ifCode == null ? null : ifCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.IF_name
     *
     * @return the value of if_define.IF_name
     *
     * @mbggenerated
     */
    public String getIfName() {
        return ifName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.IF_name
     *
     * @param ifName the value for if_define.IF_name
     *
     * @mbggenerated
     */
    public void setIfName(String ifName) {
        this.ifName = ifName == null ? null : ifName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.Status
     *
     * @return the value of if_define.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.Status
     *
     * @param status the value for if_define.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.Error_retry_times
     *
     * @return the value of if_define.Error_retry_times
     *
     * @mbggenerated
     */
    public Integer getErrorRetryTimes() {
        return errorRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.Error_retry_times
     *
     * @param errorRetryTimes the value for if_define.Error_retry_times
     *
     * @mbggenerated
     */
    public void setErrorRetryTimes(Integer errorRetryTimes) {
        this.errorRetryTimes = errorRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.Retry_wait_seconds
     *
     * @return the value of if_define.Retry_wait_seconds
     *
     * @mbggenerated
     */
    public Integer getRetryWaitSeconds() {
        return retryWaitSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.Retry_wait_seconds
     *
     * @param retryWaitSeconds the value for if_define.Retry_wait_seconds
     *
     * @mbggenerated
     */
    public void setRetryWaitSeconds(Integer retryWaitSeconds) {
        this.retryWaitSeconds = retryWaitSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.Run_method
     *
     * @return the value of if_define.Run_method
     *
     * @mbggenerated
     */
    public String getRunMethod() {
        return runMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.Run_method
     *
     * @param runMethod the value for if_define.Run_method
     *
     * @mbggenerated
     */
    public void setRunMethod(String runMethod) {
        this.runMethod = runMethod == null ? null : runMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.Class_name
     *
     * @return the value of if_define.Class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.Class_name
     *
     * @param className the value for if_define.Class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.If_type
     *
     * @return the value of if_define.If_type
     *
     * @mbggenerated
     */
    public String getIfType() {
        return ifType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.If_type
     *
     * @param ifType the value for if_define.If_type
     *
     * @mbggenerated
     */
    public void setIfType(String ifType) {
        this.ifType = ifType == null ? null : ifType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.Class_type
     *
     * @return the value of if_define.Class_type
     *
     * @mbggenerated
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.Class_type
     *
     * @param classType the value for if_define.Class_type
     *
     * @mbggenerated
     */
    public void setClassType(String classType) {
        this.classType = classType == null ? null : classType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.ctime
     *
     * @return the value of if_define.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.ctime
     *
     * @param ctime the value for if_define.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.cuser
     *
     * @return the value of if_define.cuser
     *
     * @mbggenerated
     */
    public String getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.cuser
     *
     * @param cuser the value for if_define.cuser
     *
     * @mbggenerated
     */
    public void setCuser(String cuser) {
        this.cuser = cuser == null ? null : cuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.mtime
     *
     * @return the value of if_define.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.mtime
     *
     * @param mtime the value for if_define.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.muser
     *
     * @return the value of if_define.muser
     *
     * @mbggenerated
     */
    public String getMuser() {
        return muser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.muser
     *
     * @param muser the value for if_define.muser
     *
     * @mbggenerated
     */
    public void setMuser(String muser) {
        this.muser = muser == null ? null : muser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column if_define.if_cat
     *
     * @return the value of if_define.if_cat
     *
     * @mbggenerated
     */
    public String getIfCat() {
        return ifCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column if_define.if_cat
     *
     * @param ifCat the value for if_define.if_cat
     *
     * @mbggenerated
     */
    public void setIfCat(String ifCat) {
        this.ifCat = ifCat == null ? null : ifCat.trim();
    }
}