package com.sunmw.web.domain;

import java.math.BigDecimal;
import java.util.Date;

public class OrderHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.order_head_id
     *
     * @mbggenerated
     */
    private Integer orderHeadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.order_type
     *
     * @mbggenerated
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.orig_order_no
     *
     * @mbggenerated
     */
    private String origOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.orig_order_type
     *
     * @mbggenerated
     */
    private String origOrderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.ref_order_id
     *
     * @mbggenerated
     */
    private Integer refOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.ref_order_type
     *
     * @mbggenerated
     */
    private String refOrderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.orig_order_status
     *
     * @mbggenerated
     */
    private String origOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.order_status
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.order_date
     *
     * @mbggenerated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.request_date
     *
     * @mbggenerated
     */
    private Date requestDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.delivery_date
     *
     * @mbggenerated
     */
    private Date deliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.complete_date
     *
     * @mbggenerated
     */
    private Date completeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.invoice_id
     *
     * @mbggenerated
     */
    private Integer invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.order_amt
     *
     * @mbggenerated
     */
    private BigDecimal orderAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receive_field1
     *
     * @mbggenerated
     */
    private String receiveField1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receive_field2
     *
     * @mbggenerated
     */
    private String receiveField2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receive_field3
     *
     * @mbggenerated
     */
    private String receiveField3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receive_field4
     *
     * @mbggenerated
     */
    private String receiveField4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receive_field5
     *
     * @mbggenerated
     */
    private String receiveField5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receive_field6
     *
     * @mbggenerated
     */
    private String receiveField6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.ref_order_no
     *
     * @mbggenerated
     */
    private String refOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.origin
     *
     * @mbggenerated
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.inv_status
     *
     * @mbggenerated
     */
    private String invStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.company_id
     *
     * @mbggenerated
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.payment
     *
     * @mbggenerated
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.total_fee
     *
     * @mbggenerated
     */
    private BigDecimal totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.post_fee
     *
     * @mbggenerated
     */
    private BigDecimal postFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.discount
     *
     * @mbggenerated
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.payment_point
     *
     * @mbggenerated
     */
    private Integer paymentPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.buyer_nick
     *
     * @mbggenerated
     */
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.buyer_email
     *
     * @mbggenerated
     */
    private String buyerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.post_method
     *
     * @mbggenerated
     */
    private String postMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.post_company
     *
     * @mbggenerated
     */
    private String postCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.post_no
     *
     * @mbggenerated
     */
    private String postNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_state
     *
     * @mbggenerated
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_city
     *
     * @mbggenerated
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_district
     *
     * @mbggenerated
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_address
     *
     * @mbggenerated
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_mobile
     *
     * @mbggenerated
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_tel
     *
     * @mbggenerated
     */
    private String receiverTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.seller_nick
     *
     * @mbggenerated
     */
    private String sellerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.invoice_type
     *
     * @mbggenerated
     */
    private String invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.invoice_title
     *
     * @mbggenerated
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.invoice_content
     *
     * @mbggenerated
     */
    private String invoiceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.receiver_zip
     *
     * @mbggenerated
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.post_nos
     *
     * @mbggenerated
     */
    private String postNos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.pay_time
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.pay_no
     *
     * @mbggenerated
     */
    private String payNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.order_head_id
     *
     * @return the value of order_head.order_head_id
     *
     * @mbggenerated
     */
    public Integer getOrderHeadId() {
        return orderHeadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.order_head_id
     *
     * @param orderHeadId the value for order_head.order_head_id
     *
     * @mbggenerated
     */
    public void setOrderHeadId(Integer orderHeadId) {
        this.orderHeadId = orderHeadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.order_no
     *
     * @return the value of order_head.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.order_no
     *
     * @param orderNo the value for order_head.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.order_type
     *
     * @return the value of order_head.order_type
     *
     * @mbggenerated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.order_type
     *
     * @param orderType the value for order_head.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.orig_order_no
     *
     * @return the value of order_head.orig_order_no
     *
     * @mbggenerated
     */
    public String getOrigOrderNo() {
        return origOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.orig_order_no
     *
     * @param origOrderNo the value for order_head.orig_order_no
     *
     * @mbggenerated
     */
    public void setOrigOrderNo(String origOrderNo) {
        this.origOrderNo = origOrderNo == null ? null : origOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.orig_order_type
     *
     * @return the value of order_head.orig_order_type
     *
     * @mbggenerated
     */
    public String getOrigOrderType() {
        return origOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.orig_order_type
     *
     * @param origOrderType the value for order_head.orig_order_type
     *
     * @mbggenerated
     */
    public void setOrigOrderType(String origOrderType) {
        this.origOrderType = origOrderType == null ? null : origOrderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.ref_order_id
     *
     * @return the value of order_head.ref_order_id
     *
     * @mbggenerated
     */
    public Integer getRefOrderId() {
        return refOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.ref_order_id
     *
     * @param refOrderId the value for order_head.ref_order_id
     *
     * @mbggenerated
     */
    public void setRefOrderId(Integer refOrderId) {
        this.refOrderId = refOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.ref_order_type
     *
     * @return the value of order_head.ref_order_type
     *
     * @mbggenerated
     */
    public String getRefOrderType() {
        return refOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.ref_order_type
     *
     * @param refOrderType the value for order_head.ref_order_type
     *
     * @mbggenerated
     */
    public void setRefOrderType(String refOrderType) {
        this.refOrderType = refOrderType == null ? null : refOrderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.store_id
     *
     * @return the value of order_head.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.store_id
     *
     * @param storeId the value for order_head.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.orig_order_status
     *
     * @return the value of order_head.orig_order_status
     *
     * @mbggenerated
     */
    public String getOrigOrderStatus() {
        return origOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.orig_order_status
     *
     * @param origOrderStatus the value for order_head.orig_order_status
     *
     * @mbggenerated
     */
    public void setOrigOrderStatus(String origOrderStatus) {
        this.origOrderStatus = origOrderStatus == null ? null : origOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.order_status
     *
     * @return the value of order_head.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.order_status
     *
     * @param orderStatus the value for order_head.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.order_date
     *
     * @return the value of order_head.order_date
     *
     * @mbggenerated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.order_date
     *
     * @param orderDate the value for order_head.order_date
     *
     * @mbggenerated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.request_date
     *
     * @return the value of order_head.request_date
     *
     * @mbggenerated
     */
    public Date getRequestDate() {
        return requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.request_date
     *
     * @param requestDate the value for order_head.request_date
     *
     * @mbggenerated
     */
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.delivery_date
     *
     * @return the value of order_head.delivery_date
     *
     * @mbggenerated
     */
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.delivery_date
     *
     * @param deliveryDate the value for order_head.delivery_date
     *
     * @mbggenerated
     */
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.complete_date
     *
     * @return the value of order_head.complete_date
     *
     * @mbggenerated
     */
    public Date getCompleteDate() {
        return completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.complete_date
     *
     * @param completeDate the value for order_head.complete_date
     *
     * @mbggenerated
     */
    public void setCompleteDate(Date completeDate) {
        this.completeDate = completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.invoice_id
     *
     * @return the value of order_head.invoice_id
     *
     * @mbggenerated
     */
    public Integer getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.invoice_id
     *
     * @param invoiceId the value for order_head.invoice_id
     *
     * @mbggenerated
     */
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.order_amt
     *
     * @return the value of order_head.order_amt
     *
     * @mbggenerated
     */
    public BigDecimal getOrderAmt() {
        return orderAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.order_amt
     *
     * @param orderAmt the value for order_head.order_amt
     *
     * @mbggenerated
     */
    public void setOrderAmt(BigDecimal orderAmt) {
        this.orderAmt = orderAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receive_field1
     *
     * @return the value of order_head.receive_field1
     *
     * @mbggenerated
     */
    public String getReceiveField1() {
        return receiveField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receive_field1
     *
     * @param receiveField1 the value for order_head.receive_field1
     *
     * @mbggenerated
     */
    public void setReceiveField1(String receiveField1) {
        this.receiveField1 = receiveField1 == null ? null : receiveField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receive_field2
     *
     * @return the value of order_head.receive_field2
     *
     * @mbggenerated
     */
    public String getReceiveField2() {
        return receiveField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receive_field2
     *
     * @param receiveField2 the value for order_head.receive_field2
     *
     * @mbggenerated
     */
    public void setReceiveField2(String receiveField2) {
        this.receiveField2 = receiveField2 == null ? null : receiveField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receive_field3
     *
     * @return the value of order_head.receive_field3
     *
     * @mbggenerated
     */
    public String getReceiveField3() {
        return receiveField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receive_field3
     *
     * @param receiveField3 the value for order_head.receive_field3
     *
     * @mbggenerated
     */
    public void setReceiveField3(String receiveField3) {
        this.receiveField3 = receiveField3 == null ? null : receiveField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receive_field4
     *
     * @return the value of order_head.receive_field4
     *
     * @mbggenerated
     */
    public String getReceiveField4() {
        return receiveField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receive_field4
     *
     * @param receiveField4 the value for order_head.receive_field4
     *
     * @mbggenerated
     */
    public void setReceiveField4(String receiveField4) {
        this.receiveField4 = receiveField4 == null ? null : receiveField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receive_field5
     *
     * @return the value of order_head.receive_field5
     *
     * @mbggenerated
     */
    public String getReceiveField5() {
        return receiveField5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receive_field5
     *
     * @param receiveField5 the value for order_head.receive_field5
     *
     * @mbggenerated
     */
    public void setReceiveField5(String receiveField5) {
        this.receiveField5 = receiveField5 == null ? null : receiveField5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receive_field6
     *
     * @return the value of order_head.receive_field6
     *
     * @mbggenerated
     */
    public String getReceiveField6() {
        return receiveField6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receive_field6
     *
     * @param receiveField6 the value for order_head.receive_field6
     *
     * @mbggenerated
     */
    public void setReceiveField6(String receiveField6) {
        this.receiveField6 = receiveField6 == null ? null : receiveField6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.ctime
     *
     * @return the value of order_head.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.ctime
     *
     * @param ctime the value for order_head.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.mtime
     *
     * @return the value of order_head.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.mtime
     *
     * @param mtime the value for order_head.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.ref_order_no
     *
     * @return the value of order_head.ref_order_no
     *
     * @mbggenerated
     */
    public String getRefOrderNo() {
        return refOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.ref_order_no
     *
     * @param refOrderNo the value for order_head.ref_order_no
     *
     * @mbggenerated
     */
    public void setRefOrderNo(String refOrderNo) {
        this.refOrderNo = refOrderNo == null ? null : refOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.origin
     *
     * @return the value of order_head.origin
     *
     * @mbggenerated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.origin
     *
     * @param origin the value for order_head.origin
     *
     * @mbggenerated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.inv_status
     *
     * @return the value of order_head.inv_status
     *
     * @mbggenerated
     */
    public String getInvStatus() {
        return invStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.inv_status
     *
     * @param invStatus the value for order_head.inv_status
     *
     * @mbggenerated
     */
    public void setInvStatus(String invStatus) {
        this.invStatus = invStatus == null ? null : invStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.company_id
     *
     * @return the value of order_head.company_id
     *
     * @mbggenerated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.company_id
     *
     * @param companyId the value for order_head.company_id
     *
     * @mbggenerated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.payment
     *
     * @return the value of order_head.payment
     *
     * @mbggenerated
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.payment
     *
     * @param payment the value for order_head.payment
     *
     * @mbggenerated
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.total_fee
     *
     * @return the value of order_head.total_fee
     *
     * @mbggenerated
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.total_fee
     *
     * @param totalFee the value for order_head.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.post_fee
     *
     * @return the value of order_head.post_fee
     *
     * @mbggenerated
     */
    public BigDecimal getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.post_fee
     *
     * @param postFee the value for order_head.post_fee
     *
     * @mbggenerated
     */
    public void setPostFee(BigDecimal postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.discount
     *
     * @return the value of order_head.discount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.discount
     *
     * @param discount the value for order_head.discount
     *
     * @mbggenerated
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.payment_point
     *
     * @return the value of order_head.payment_point
     *
     * @mbggenerated
     */
    public Integer getPaymentPoint() {
        return paymentPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.payment_point
     *
     * @param paymentPoint the value for order_head.payment_point
     *
     * @mbggenerated
     */
    public void setPaymentPoint(Integer paymentPoint) {
        this.paymentPoint = paymentPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.buyer_nick
     *
     * @return the value of order_head.buyer_nick
     *
     * @mbggenerated
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.buyer_nick
     *
     * @param buyerNick the value for order_head.buyer_nick
     *
     * @mbggenerated
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.buyer_email
     *
     * @return the value of order_head.buyer_email
     *
     * @mbggenerated
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.buyer_email
     *
     * @param buyerEmail the value for order_head.buyer_email
     *
     * @mbggenerated
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.post_method
     *
     * @return the value of order_head.post_method
     *
     * @mbggenerated
     */
    public String getPostMethod() {
        return postMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.post_method
     *
     * @param postMethod the value for order_head.post_method
     *
     * @mbggenerated
     */
    public void setPostMethod(String postMethod) {
        this.postMethod = postMethod == null ? null : postMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.post_company
     *
     * @return the value of order_head.post_company
     *
     * @mbggenerated
     */
    public String getPostCompany() {
        return postCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.post_company
     *
     * @param postCompany the value for order_head.post_company
     *
     * @mbggenerated
     */
    public void setPostCompany(String postCompany) {
        this.postCompany = postCompany == null ? null : postCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.post_no
     *
     * @return the value of order_head.post_no
     *
     * @mbggenerated
     */
    public String getPostNo() {
        return postNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.post_no
     *
     * @param postNo the value for order_head.post_no
     *
     * @mbggenerated
     */
    public void setPostNo(String postNo) {
        this.postNo = postNo == null ? null : postNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_state
     *
     * @return the value of order_head.receiver_state
     *
     * @mbggenerated
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_state
     *
     * @param receiverState the value for order_head.receiver_state
     *
     * @mbggenerated
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_city
     *
     * @return the value of order_head.receiver_city
     *
     * @mbggenerated
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_city
     *
     * @param receiverCity the value for order_head.receiver_city
     *
     * @mbggenerated
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_district
     *
     * @return the value of order_head.receiver_district
     *
     * @mbggenerated
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_district
     *
     * @param receiverDistrict the value for order_head.receiver_district
     *
     * @mbggenerated
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_address
     *
     * @return the value of order_head.receiver_address
     *
     * @mbggenerated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_address
     *
     * @param receiverAddress the value for order_head.receiver_address
     *
     * @mbggenerated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_name
     *
     * @return the value of order_head.receiver_name
     *
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_name
     *
     * @param receiverName the value for order_head.receiver_name
     *
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_mobile
     *
     * @return the value of order_head.receiver_mobile
     *
     * @mbggenerated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_mobile
     *
     * @param receiverMobile the value for order_head.receiver_mobile
     *
     * @mbggenerated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_tel
     *
     * @return the value of order_head.receiver_tel
     *
     * @mbggenerated
     */
    public String getReceiverTel() {
        return receiverTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_tel
     *
     * @param receiverTel the value for order_head.receiver_tel
     *
     * @mbggenerated
     */
    public void setReceiverTel(String receiverTel) {
        this.receiverTel = receiverTel == null ? null : receiverTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.seller_nick
     *
     * @return the value of order_head.seller_nick
     *
     * @mbggenerated
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.seller_nick
     *
     * @param sellerNick the value for order_head.seller_nick
     *
     * @mbggenerated
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.invoice_type
     *
     * @return the value of order_head.invoice_type
     *
     * @mbggenerated
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.invoice_type
     *
     * @param invoiceType the value for order_head.invoice_type
     *
     * @mbggenerated
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType == null ? null : invoiceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.invoice_title
     *
     * @return the value of order_head.invoice_title
     *
     * @mbggenerated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.invoice_title
     *
     * @param invoiceTitle the value for order_head.invoice_title
     *
     * @mbggenerated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.invoice_content
     *
     * @return the value of order_head.invoice_content
     *
     * @mbggenerated
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.invoice_content
     *
     * @param invoiceContent the value for order_head.invoice_content
     *
     * @mbggenerated
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.receiver_zip
     *
     * @return the value of order_head.receiver_zip
     *
     * @mbggenerated
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.receiver_zip
     *
     * @param receiverZip the value for order_head.receiver_zip
     *
     * @mbggenerated
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.post_nos
     *
     * @return the value of order_head.post_nos
     *
     * @mbggenerated
     */
    public String getPostNos() {
        return postNos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.post_nos
     *
     * @param postNos the value for order_head.post_nos
     *
     * @mbggenerated
     */
    public void setPostNos(String postNos) {
        this.postNos = postNos == null ? null : postNos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.pay_time
     *
     * @return the value of order_head.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.pay_time
     *
     * @param payTime the value for order_head.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.pay_no
     *
     * @return the value of order_head.pay_no
     *
     * @mbggenerated
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.pay_no
     *
     * @param payNo the value for order_head.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }
}