package com.sunmw.web.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_item
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_item
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_item
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public OrderItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_item
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderItemIdIsNull() {
            addCriterion("order_item_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNotNull() {
            addCriterion("order_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdEqualTo(Integer value) {
            addCriterion("order_item_id =", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotEqualTo(Integer value) {
            addCriterion("order_item_id <>", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThan(Integer value) {
            addCriterion("order_item_id >", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_item_id >=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThan(Integer value) {
            addCriterion("order_item_id <", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_item_id <=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIn(List<Integer> values) {
            addCriterion("order_item_id in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotIn(List<Integer> values) {
            addCriterion("order_item_id not in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdBetween(Integer value1, Integer value2) {
            addCriterion("order_item_id between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_item_id not between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdIsNull() {
            addCriterion("order_head_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdIsNotNull() {
            addCriterion("order_head_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdEqualTo(Integer value) {
            addCriterion("order_head_id =", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotEqualTo(Integer value) {
            addCriterion("order_head_id <>", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdGreaterThan(Integer value) {
            addCriterion("order_head_id >", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_head_id >=", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdLessThan(Integer value) {
            addCriterion("order_head_id <", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_head_id <=", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdIn(List<Integer> values) {
            addCriterion("order_head_id in", values, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotIn(List<Integer> values) {
            addCriterion("order_head_id not in", values, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdBetween(Integer value1, Integer value2) {
            addCriterion("order_head_id between", value1, value2, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_head_id not between", value1, value2, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNull() {
            addCriterion("sku_cd is null");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNotNull() {
            addCriterion("sku_cd is not null");
            return (Criteria) this;
        }

        public Criteria andSkuCdEqualTo(String value) {
            addCriterion("sku_cd =", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotEqualTo(String value) {
            addCriterion("sku_cd <>", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThan(String value) {
            addCriterion("sku_cd >", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThanOrEqualTo(String value) {
            addCriterion("sku_cd >=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThan(String value) {
            addCriterion("sku_cd <", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThanOrEqualTo(String value) {
            addCriterion("sku_cd <=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLike(String value) {
            addCriterion("sku_cd like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotLike(String value) {
            addCriterion("sku_cd not like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdIn(List<String> values) {
            addCriterion("sku_cd in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotIn(List<String> values) {
            addCriterion("sku_cd not in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdBetween(String value1, String value2) {
            addCriterion("sku_cd between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotBetween(String value1, String value2) {
            addCriterion("sku_cd not between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andItemCdIsNull() {
            addCriterion("item_cd is null");
            return (Criteria) this;
        }

        public Criteria andItemCdIsNotNull() {
            addCriterion("item_cd is not null");
            return (Criteria) this;
        }

        public Criteria andItemCdEqualTo(String value) {
            addCriterion("item_cd =", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotEqualTo(String value) {
            addCriterion("item_cd <>", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdGreaterThan(String value) {
            addCriterion("item_cd >", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdGreaterThanOrEqualTo(String value) {
            addCriterion("item_cd >=", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLessThan(String value) {
            addCriterion("item_cd <", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLessThanOrEqualTo(String value) {
            addCriterion("item_cd <=", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLike(String value) {
            addCriterion("item_cd like", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotLike(String value) {
            addCriterion("item_cd not like", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdIn(List<String> values) {
            addCriterion("item_cd in", values, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotIn(List<String> values) {
            addCriterion("item_cd not in", values, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdBetween(String value1, String value2) {
            addCriterion("item_cd between", value1, value2, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotBetween(String value1, String value2) {
            addCriterion("item_cd not between", value1, value2, "itemCd");
            return (Criteria) this;
        }

        public Criteria andSkuProp1IsNull() {
            addCriterion("sku_prop1 is null");
            return (Criteria) this;
        }

        public Criteria andSkuProp1IsNotNull() {
            addCriterion("sku_prop1 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuProp1EqualTo(String value) {
            addCriterion("sku_prop1 =", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotEqualTo(String value) {
            addCriterion("sku_prop1 <>", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1GreaterThan(String value) {
            addCriterion("sku_prop1 >", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1GreaterThanOrEqualTo(String value) {
            addCriterion("sku_prop1 >=", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1LessThan(String value) {
            addCriterion("sku_prop1 <", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1LessThanOrEqualTo(String value) {
            addCriterion("sku_prop1 <=", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1Like(String value) {
            addCriterion("sku_prop1 like", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotLike(String value) {
            addCriterion("sku_prop1 not like", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1In(List<String> values) {
            addCriterion("sku_prop1 in", values, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotIn(List<String> values) {
            addCriterion("sku_prop1 not in", values, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1Between(String value1, String value2) {
            addCriterion("sku_prop1 between", value1, value2, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotBetween(String value1, String value2) {
            addCriterion("sku_prop1 not between", value1, value2, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp2IsNull() {
            addCriterion("sku_prop2 is null");
            return (Criteria) this;
        }

        public Criteria andSkuProp2IsNotNull() {
            addCriterion("sku_prop2 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuProp2EqualTo(String value) {
            addCriterion("sku_prop2 =", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotEqualTo(String value) {
            addCriterion("sku_prop2 <>", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2GreaterThan(String value) {
            addCriterion("sku_prop2 >", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2GreaterThanOrEqualTo(String value) {
            addCriterion("sku_prop2 >=", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2LessThan(String value) {
            addCriterion("sku_prop2 <", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2LessThanOrEqualTo(String value) {
            addCriterion("sku_prop2 <=", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2Like(String value) {
            addCriterion("sku_prop2 like", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotLike(String value) {
            addCriterion("sku_prop2 not like", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2In(List<String> values) {
            addCriterion("sku_prop2 in", values, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotIn(List<String> values) {
            addCriterion("sku_prop2 not in", values, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2Between(String value1, String value2) {
            addCriterion("sku_prop2 between", value1, value2, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotBetween(String value1, String value2) {
            addCriterion("sku_prop2 not between", value1, value2, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp3IsNull() {
            addCriterion("sku_prop3 is null");
            return (Criteria) this;
        }

        public Criteria andSkuProp3IsNotNull() {
            addCriterion("sku_prop3 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuProp3EqualTo(String value) {
            addCriterion("sku_prop3 =", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotEqualTo(String value) {
            addCriterion("sku_prop3 <>", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3GreaterThan(String value) {
            addCriterion("sku_prop3 >", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3GreaterThanOrEqualTo(String value) {
            addCriterion("sku_prop3 >=", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3LessThan(String value) {
            addCriterion("sku_prop3 <", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3LessThanOrEqualTo(String value) {
            addCriterion("sku_prop3 <=", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3Like(String value) {
            addCriterion("sku_prop3 like", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotLike(String value) {
            addCriterion("sku_prop3 not like", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3In(List<String> values) {
            addCriterion("sku_prop3 in", values, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotIn(List<String> values) {
            addCriterion("sku_prop3 not in", values, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3Between(String value1, String value2) {
            addCriterion("sku_prop3 between", value1, value2, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotBetween(String value1, String value2) {
            addCriterion("sku_prop3 not between", value1, value2, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andReqQtyIsNull() {
            addCriterion("req_qty is null");
            return (Criteria) this;
        }

        public Criteria andReqQtyIsNotNull() {
            addCriterion("req_qty is not null");
            return (Criteria) this;
        }

        public Criteria andReqQtyEqualTo(Long value) {
            addCriterion("req_qty =", value, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyNotEqualTo(Long value) {
            addCriterion("req_qty <>", value, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyGreaterThan(Long value) {
            addCriterion("req_qty >", value, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyGreaterThanOrEqualTo(Long value) {
            addCriterion("req_qty >=", value, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyLessThan(Long value) {
            addCriterion("req_qty <", value, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyLessThanOrEqualTo(Long value) {
            addCriterion("req_qty <=", value, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyIn(List<Long> values) {
            addCriterion("req_qty in", values, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyNotIn(List<Long> values) {
            addCriterion("req_qty not in", values, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyBetween(Long value1, Long value2) {
            addCriterion("req_qty between", value1, value2, "reqQty");
            return (Criteria) this;
        }

        public Criteria andReqQtyNotBetween(Long value1, Long value2) {
            addCriterion("req_qty not between", value1, value2, "reqQty");
            return (Criteria) this;
        }

        public Criteria andQtyIsNull() {
            addCriterion("qty is null");
            return (Criteria) this;
        }

        public Criteria andQtyIsNotNull() {
            addCriterion("qty is not null");
            return (Criteria) this;
        }

        public Criteria andQtyEqualTo(Long value) {
            addCriterion("qty =", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotEqualTo(Long value) {
            addCriterion("qty <>", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThan(Long value) {
            addCriterion("qty >", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThanOrEqualTo(Long value) {
            addCriterion("qty >=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThan(Long value) {
            addCriterion("qty <", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThanOrEqualTo(Long value) {
            addCriterion("qty <=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyIn(List<Long> values) {
            addCriterion("qty in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotIn(List<Long> values) {
            addCriterion("qty not in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyBetween(Long value1, Long value2) {
            addCriterion("qty between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotBetween(Long value1, Long value2) {
            addCriterion("qty not between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusIsNull() {
            addCriterion("order_item_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusIsNotNull() {
            addCriterion("order_item_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusEqualTo(String value) {
            addCriterion("order_item_status =", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusNotEqualTo(String value) {
            addCriterion("order_item_status <>", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusGreaterThan(String value) {
            addCriterion("order_item_status >", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusGreaterThanOrEqualTo(String value) {
            addCriterion("order_item_status >=", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusLessThan(String value) {
            addCriterion("order_item_status <", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusLessThanOrEqualTo(String value) {
            addCriterion("order_item_status <=", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusLike(String value) {
            addCriterion("order_item_status like", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusNotLike(String value) {
            addCriterion("order_item_status not like", value, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusIn(List<String> values) {
            addCriterion("order_item_status in", values, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusNotIn(List<String> values) {
            addCriterion("order_item_status not in", values, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusBetween(String value1, String value2) {
            addCriterion("order_item_status between", value1, value2, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andOrderItemStatusNotBetween(String value1, String value2) {
            addCriterion("order_item_status not between", value1, value2, "orderItemStatus");
            return (Criteria) this;
        }

        public Criteria andSubTotalIsNull() {
            addCriterion("sub_total is null");
            return (Criteria) this;
        }

        public Criteria andSubTotalIsNotNull() {
            addCriterion("sub_total is not null");
            return (Criteria) this;
        }

        public Criteria andSubTotalEqualTo(BigDecimal value) {
            addCriterion("sub_total =", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotEqualTo(BigDecimal value) {
            addCriterion("sub_total <>", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalGreaterThan(BigDecimal value) {
            addCriterion("sub_total >", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sub_total >=", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalLessThan(BigDecimal value) {
            addCriterion("sub_total <", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sub_total <=", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalIn(List<BigDecimal> values) {
            addCriterion("sub_total in", values, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotIn(List<BigDecimal> values) {
            addCriterion("sub_total not in", values, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sub_total between", value1, value2, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sub_total not between", value1, value2, "subTotal");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdIsNull() {
            addCriterion("red_order_item_id is null");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdIsNotNull() {
            addCriterion("red_order_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdEqualTo(Integer value) {
            addCriterion("red_order_item_id =", value, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdNotEqualTo(Integer value) {
            addCriterion("red_order_item_id <>", value, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdGreaterThan(Integer value) {
            addCriterion("red_order_item_id >", value, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("red_order_item_id >=", value, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdLessThan(Integer value) {
            addCriterion("red_order_item_id <", value, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("red_order_item_id <=", value, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdIn(List<Integer> values) {
            addCriterion("red_order_item_id in", values, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdNotIn(List<Integer> values) {
            addCriterion("red_order_item_id not in", values, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdBetween(Integer value1, Integer value2) {
            addCriterion("red_order_item_id between", value1, value2, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andRedOrderItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("red_order_item_id not between", value1, value2, "redOrderItemId");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoIsNull() {
            addCriterion("orig_order_item_no is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoIsNotNull() {
            addCriterion("orig_order_item_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoEqualTo(String value) {
            addCriterion("orig_order_item_no =", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotEqualTo(String value) {
            addCriterion("orig_order_item_no <>", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoGreaterThan(String value) {
            addCriterion("orig_order_item_no >", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoGreaterThanOrEqualTo(String value) {
            addCriterion("orig_order_item_no >=", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoLessThan(String value) {
            addCriterion("orig_order_item_no <", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoLessThanOrEqualTo(String value) {
            addCriterion("orig_order_item_no <=", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoLike(String value) {
            addCriterion("orig_order_item_no like", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotLike(String value) {
            addCriterion("orig_order_item_no not like", value, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoIn(List<String> values) {
            addCriterion("orig_order_item_no in", values, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotIn(List<String> values) {
            addCriterion("orig_order_item_no not in", values, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoBetween(String value1, String value2) {
            addCriterion("orig_order_item_no between", value1, value2, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderItemNoNotBetween(String value1, String value2) {
            addCriterion("orig_order_item_no not between", value1, value2, "origOrderItemNo");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdIsNull() {
            addCriterion("orig_sku_id is null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdIsNotNull() {
            addCriterion("orig_sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdEqualTo(String value) {
            addCriterion("orig_sku_id =", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotEqualTo(String value) {
            addCriterion("orig_sku_id <>", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdGreaterThan(String value) {
            addCriterion("orig_sku_id >", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdGreaterThanOrEqualTo(String value) {
            addCriterion("orig_sku_id >=", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdLessThan(String value) {
            addCriterion("orig_sku_id <", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdLessThanOrEqualTo(String value) {
            addCriterion("orig_sku_id <=", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdLike(String value) {
            addCriterion("orig_sku_id like", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotLike(String value) {
            addCriterion("orig_sku_id not like", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdIn(List<String> values) {
            addCriterion("orig_sku_id in", values, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotIn(List<String> values) {
            addCriterion("orig_sku_id not in", values, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdBetween(String value1, String value2) {
            addCriterion("orig_sku_id between", value1, value2, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotBetween(String value1, String value2) {
            addCriterion("orig_sku_id not between", value1, value2, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeIsNull() {
            addCriterion("order_item_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeIsNotNull() {
            addCriterion("order_item_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeEqualTo(String value) {
            addCriterion("order_item_type =", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeNotEqualTo(String value) {
            addCriterion("order_item_type <>", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeGreaterThan(String value) {
            addCriterion("order_item_type >", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_item_type >=", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeLessThan(String value) {
            addCriterion("order_item_type <", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeLessThanOrEqualTo(String value) {
            addCriterion("order_item_type <=", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeLike(String value) {
            addCriterion("order_item_type like", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeNotLike(String value) {
            addCriterion("order_item_type not like", value, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeIn(List<String> values) {
            addCriterion("order_item_type in", values, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeNotIn(List<String> values) {
            addCriterion("order_item_type not in", values, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeBetween(String value1, String value2) {
            addCriterion("order_item_type between", value1, value2, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemTypeNotBetween(String value1, String value2) {
            addCriterion("order_item_type not between", value1, value2, "orderItemType");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoIsNull() {
            addCriterion("order_item_memo is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoIsNotNull() {
            addCriterion("order_item_memo is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoEqualTo(String value) {
            addCriterion("order_item_memo =", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoNotEqualTo(String value) {
            addCriterion("order_item_memo <>", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoGreaterThan(String value) {
            addCriterion("order_item_memo >", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoGreaterThanOrEqualTo(String value) {
            addCriterion("order_item_memo >=", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoLessThan(String value) {
            addCriterion("order_item_memo <", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoLessThanOrEqualTo(String value) {
            addCriterion("order_item_memo <=", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoLike(String value) {
            addCriterion("order_item_memo like", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoNotLike(String value) {
            addCriterion("order_item_memo not like", value, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoIn(List<String> values) {
            addCriterion("order_item_memo in", values, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoNotIn(List<String> values) {
            addCriterion("order_item_memo not in", values, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoBetween(String value1, String value2) {
            addCriterion("order_item_memo between", value1, value2, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andOrderItemMemoNotBetween(String value1, String value2) {
            addCriterion("order_item_memo not between", value1, value2, "orderItemMemo");
            return (Criteria) this;
        }

        public Criteria andRefQtyIsNull() {
            addCriterion("ref_qty is null");
            return (Criteria) this;
        }

        public Criteria andRefQtyIsNotNull() {
            addCriterion("ref_qty is not null");
            return (Criteria) this;
        }

        public Criteria andRefQtyEqualTo(Long value) {
            addCriterion("ref_qty =", value, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyNotEqualTo(Long value) {
            addCriterion("ref_qty <>", value, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyGreaterThan(Long value) {
            addCriterion("ref_qty >", value, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyGreaterThanOrEqualTo(Long value) {
            addCriterion("ref_qty >=", value, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyLessThan(Long value) {
            addCriterion("ref_qty <", value, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyLessThanOrEqualTo(Long value) {
            addCriterion("ref_qty <=", value, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyIn(List<Long> values) {
            addCriterion("ref_qty in", values, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyNotIn(List<Long> values) {
            addCriterion("ref_qty not in", values, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyBetween(Long value1, Long value2) {
            addCriterion("ref_qty between", value1, value2, "refQty");
            return (Criteria) this;
        }

        public Criteria andRefQtyNotBetween(Long value1, Long value2) {
            addCriterion("ref_qty not between", value1, value2, "refQty");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNull() {
            addCriterion("discount_price is null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNotNull() {
            addCriterion("discount_price is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceEqualTo(BigDecimal value) {
            addCriterion("discount_price =", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotEqualTo(BigDecimal value) {
            addCriterion("discount_price <>", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThan(BigDecimal value) {
            addCriterion("discount_price >", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price >=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThan(BigDecimal value) {
            addCriterion("discount_price <", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price <=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIn(List<BigDecimal> values) {
            addCriterion("discount_price in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotIn(List<BigDecimal> values) {
            addCriterion("discount_price not in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price not between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceIsNull() {
            addCriterion("real_price is null");
            return (Criteria) this;
        }

        public Criteria andRealPriceIsNotNull() {
            addCriterion("real_price is not null");
            return (Criteria) this;
        }

        public Criteria andRealPriceEqualTo(BigDecimal value) {
            addCriterion("real_price =", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotEqualTo(BigDecimal value) {
            addCriterion("real_price <>", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceGreaterThan(BigDecimal value) {
            addCriterion("real_price >", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_price >=", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceLessThan(BigDecimal value) {
            addCriterion("real_price <", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_price <=", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceIn(List<BigDecimal> values) {
            addCriterion("real_price in", values, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotIn(List<BigDecimal> values) {
            addCriterion("real_price not in", values, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_price between", value1, value2, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_price not between", value1, value2, "realPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtIsNull() {
            addCriterion("discount_price_amt is null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtIsNotNull() {
            addCriterion("discount_price_amt is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtEqualTo(BigDecimal value) {
            addCriterion("discount_price_amt =", value, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtNotEqualTo(BigDecimal value) {
            addCriterion("discount_price_amt <>", value, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtGreaterThan(BigDecimal value) {
            addCriterion("discount_price_amt >", value, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price_amt >=", value, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtLessThan(BigDecimal value) {
            addCriterion("discount_price_amt <", value, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price_amt <=", value, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtIn(List<BigDecimal> values) {
            addCriterion("discount_price_amt in", values, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtNotIn(List<BigDecimal> values) {
            addCriterion("discount_price_amt not in", values, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price_amt between", value1, value2, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price_amt not between", value1, value2, "discountPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtIsNull() {
            addCriterion("real_price_amt is null");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtIsNotNull() {
            addCriterion("real_price_amt is not null");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtEqualTo(BigDecimal value) {
            addCriterion("real_price_amt =", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtNotEqualTo(BigDecimal value) {
            addCriterion("real_price_amt <>", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtGreaterThan(BigDecimal value) {
            addCriterion("real_price_amt >", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("real_price_amt >=", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtLessThan(BigDecimal value) {
            addCriterion("real_price_amt <", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("real_price_amt <=", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtIn(List<BigDecimal> values) {
            addCriterion("real_price_amt in", values, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtNotIn(List<BigDecimal> values) {
            addCriterion("real_price_amt not in", values, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_price_amt between", value1, value2, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("real_price_amt not between", value1, value2, "realPriceAmt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_item
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_item
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}