package com.sunmw.web.domain;

import java.util.Date;

public class TaskDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Task_id
     *
     * @mbggenerated
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.IF_id
     *
     * @mbggenerated
     */
    private Long ifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.End_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Last_start_time
     *
     * @mbggenerated
     */
    private Date lastStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Last_end_time
     *
     * @mbggenerated
     */
    private Date lastEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Is_last_success
     *
     * @mbggenerated
     */
    private String isLastSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Cycle_type
     *
     * @mbggenerated
     */
    private String cycleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Cycle
     *
     * @mbggenerated
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.store_id
     *
     * @mbggenerated
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Next_exec_time
     *
     * @mbggenerated
     */
    private Date nextExecTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Day_cycle_type
     *
     * @mbggenerated
     */
    private String dayCycleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Day_cycle
     *
     * @mbggenerated
     */
    private Date dayCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Day_start_time
     *
     * @mbggenerated
     */
    private Date dayStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Day_end_time
     *
     * @mbggenerated
     */
    private Date dayEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.cuser
     *
     * @mbggenerated
     */
    private String cuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.muser
     *
     * @mbggenerated
     */
    private String muser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.Last_exec_time
     *
     * @mbggenerated
     */
    private Date lastExecTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.cron_expression
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_define.is_load
     *
     * @mbggenerated
     */
    private String isLoad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Task_id
     *
     * @return the value of task_define.Task_id
     *
     * @mbggenerated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Task_id
     *
     * @param taskId the value for task_define.Task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.IF_id
     *
     * @return the value of task_define.IF_id
     *
     * @mbggenerated
     */
    public Long getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.IF_id
     *
     * @param ifId the value for task_define.IF_id
     *
     * @mbggenerated
     */
    public void setIfId(Long ifId) {
        this.ifId = ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Start_date
     *
     * @return the value of task_define.Start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Start_date
     *
     * @param startDate the value for task_define.Start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.End_date
     *
     * @return the value of task_define.End_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.End_date
     *
     * @param endDate the value for task_define.End_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Last_start_time
     *
     * @return the value of task_define.Last_start_time
     *
     * @mbggenerated
     */
    public Date getLastStartTime() {
        return lastStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Last_start_time
     *
     * @param lastStartTime the value for task_define.Last_start_time
     *
     * @mbggenerated
     */
    public void setLastStartTime(Date lastStartTime) {
        this.lastStartTime = lastStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Last_end_time
     *
     * @return the value of task_define.Last_end_time
     *
     * @mbggenerated
     */
    public Date getLastEndTime() {
        return lastEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Last_end_time
     *
     * @param lastEndTime the value for task_define.Last_end_time
     *
     * @mbggenerated
     */
    public void setLastEndTime(Date lastEndTime) {
        this.lastEndTime = lastEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Is_last_success
     *
     * @return the value of task_define.Is_last_success
     *
     * @mbggenerated
     */
    public String getIsLastSuccess() {
        return isLastSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Is_last_success
     *
     * @param isLastSuccess the value for task_define.Is_last_success
     *
     * @mbggenerated
     */
    public void setIsLastSuccess(String isLastSuccess) {
        this.isLastSuccess = isLastSuccess == null ? null : isLastSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Cycle_type
     *
     * @return the value of task_define.Cycle_type
     *
     * @mbggenerated
     */
    public String getCycleType() {
        return cycleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Cycle_type
     *
     * @param cycleType the value for task_define.Cycle_type
     *
     * @mbggenerated
     */
    public void setCycleType(String cycleType) {
        this.cycleType = cycleType == null ? null : cycleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Cycle
     *
     * @return the value of task_define.Cycle
     *
     * @mbggenerated
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Cycle
     *
     * @param cycle the value for task_define.Cycle
     *
     * @mbggenerated
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Status
     *
     * @return the value of task_define.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Status
     *
     * @param status the value for task_define.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.store_id
     *
     * @return the value of task_define.store_id
     *
     * @mbggenerated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.store_id
     *
     * @param storeId the value for task_define.store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Next_exec_time
     *
     * @return the value of task_define.Next_exec_time
     *
     * @mbggenerated
     */
    public Date getNextExecTime() {
        return nextExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Next_exec_time
     *
     * @param nextExecTime the value for task_define.Next_exec_time
     *
     * @mbggenerated
     */
    public void setNextExecTime(Date nextExecTime) {
        this.nextExecTime = nextExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Day_cycle_type
     *
     * @return the value of task_define.Day_cycle_type
     *
     * @mbggenerated
     */
    public String getDayCycleType() {
        return dayCycleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Day_cycle_type
     *
     * @param dayCycleType the value for task_define.Day_cycle_type
     *
     * @mbggenerated
     */
    public void setDayCycleType(String dayCycleType) {
        this.dayCycleType = dayCycleType == null ? null : dayCycleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Day_cycle
     *
     * @return the value of task_define.Day_cycle
     *
     * @mbggenerated
     */
    public Date getDayCycle() {
        return dayCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Day_cycle
     *
     * @param dayCycle the value for task_define.Day_cycle
     *
     * @mbggenerated
     */
    public void setDayCycle(Date dayCycle) {
        this.dayCycle = dayCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Day_start_time
     *
     * @return the value of task_define.Day_start_time
     *
     * @mbggenerated
     */
    public Date getDayStartTime() {
        return dayStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Day_start_time
     *
     * @param dayStartTime the value for task_define.Day_start_time
     *
     * @mbggenerated
     */
    public void setDayStartTime(Date dayStartTime) {
        this.dayStartTime = dayStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Day_end_time
     *
     * @return the value of task_define.Day_end_time
     *
     * @mbggenerated
     */
    public Date getDayEndTime() {
        return dayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Day_end_time
     *
     * @param dayEndTime the value for task_define.Day_end_time
     *
     * @mbggenerated
     */
    public void setDayEndTime(Date dayEndTime) {
        this.dayEndTime = dayEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.ctime
     *
     * @return the value of task_define.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.ctime
     *
     * @param ctime the value for task_define.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.cuser
     *
     * @return the value of task_define.cuser
     *
     * @mbggenerated
     */
    public String getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.cuser
     *
     * @param cuser the value for task_define.cuser
     *
     * @mbggenerated
     */
    public void setCuser(String cuser) {
        this.cuser = cuser == null ? null : cuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.mtime
     *
     * @return the value of task_define.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.mtime
     *
     * @param mtime the value for task_define.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.muser
     *
     * @return the value of task_define.muser
     *
     * @mbggenerated
     */
    public String getMuser() {
        return muser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.muser
     *
     * @param muser the value for task_define.muser
     *
     * @mbggenerated
     */
    public void setMuser(String muser) {
        this.muser = muser == null ? null : muser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.Last_exec_time
     *
     * @return the value of task_define.Last_exec_time
     *
     * @mbggenerated
     */
    public Date getLastExecTime() {
        return lastExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.Last_exec_time
     *
     * @param lastExecTime the value for task_define.Last_exec_time
     *
     * @mbggenerated
     */
    public void setLastExecTime(Date lastExecTime) {
        this.lastExecTime = lastExecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.cron_expression
     *
     * @return the value of task_define.cron_expression
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.cron_expression
     *
     * @param cronExpression the value for task_define.cron_expression
     *
     * @mbggenerated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_define.is_load
     *
     * @return the value of task_define.is_load
     *
     * @mbggenerated
     */
    public String getIsLoad() {
        return isLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_define.is_load
     *
     * @param isLoad the value for task_define.is_load
     *
     * @mbggenerated
     */
    public void setIsLoad(String isLoad) {
        this.isLoad = isLoad == null ? null : isLoad.trim();
    }
}