package com.sunmw.web.domain.report;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaobaoAccountDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public TaobaoAccountDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Integer value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Integer value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Integer value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Integer value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Integer> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Integer> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Integer value1, Integer value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("order_date is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(Date value) {
            addCriterion("order_date =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(Date value) {
            addCriterion("order_date <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(Date value) {
            addCriterion("order_date >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(Date value) {
            addCriterion("order_date >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(Date value) {
            addCriterion("order_date <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(Date value) {
            addCriterion("order_date <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<Date> values) {
            addCriterion("order_date in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<Date> values) {
            addCriterion("order_date not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(Date value1, Date value2) {
            addCriterion("order_date between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(Date value1, Date value2) {
            addCriterion("order_date not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateIsNull() {
            addCriterion("delivery_date is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateIsNotNull() {
            addCriterion("delivery_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateEqualTo(Date value) {
            addCriterion("delivery_date =", value, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateNotEqualTo(Date value) {
            addCriterion("delivery_date <>", value, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateGreaterThan(Date value) {
            addCriterion("delivery_date >", value, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("delivery_date >=", value, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateLessThan(Date value) {
            addCriterion("delivery_date <", value, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateLessThanOrEqualTo(Date value) {
            addCriterion("delivery_date <=", value, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateIn(List<Date> values) {
            addCriterion("delivery_date in", values, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateNotIn(List<Date> values) {
            addCriterion("delivery_date not in", values, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateBetween(Date value1, Date value2) {
            addCriterion("delivery_date between", value1, value2, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andDeliveryDateNotBetween(Date value1, Date value2) {
            addCriterion("delivery_date not between", value1, value2, "deliveryDate");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNull() {
            addCriterion("platform is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNotNull() {
            addCriterion("platform is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformEqualTo(String value) {
            addCriterion("platform =", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotEqualTo(String value) {
            addCriterion("platform <>", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThan(String value) {
            addCriterion("platform >", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThanOrEqualTo(String value) {
            addCriterion("platform >=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThan(String value) {
            addCriterion("platform <", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThanOrEqualTo(String value) {
            addCriterion("platform <=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLike(String value) {
            addCriterion("platform like", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotLike(String value) {
            addCriterion("platform not like", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformIn(List<String> values) {
            addCriterion("platform in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotIn(List<String> values) {
            addCriterion("platform not in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformBetween(String value1, String value2) {
            addCriterion("platform between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotBetween(String value1, String value2) {
            addCriterion("platform not between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("order_type is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("order_type is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("order_type =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("order_type <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("order_type >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("order_type >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("order_type <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("order_type <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("order_type like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("order_type not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("order_type in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("order_type not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("order_type between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("order_type not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderAmtIsNull() {
            addCriterion("order_amt is null");
            return (Criteria) this;
        }

        public Criteria andOrderAmtIsNotNull() {
            addCriterion("order_amt is not null");
            return (Criteria) this;
        }

        public Criteria andOrderAmtEqualTo(BigDecimal value) {
            addCriterion("order_amt =", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotEqualTo(BigDecimal value) {
            addCriterion("order_amt <>", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtGreaterThan(BigDecimal value) {
            addCriterion("order_amt >", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("order_amt >=", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtLessThan(BigDecimal value) {
            addCriterion("order_amt <", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("order_amt <=", value, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtIn(List<BigDecimal> values) {
            addCriterion("order_amt in", values, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotIn(List<BigDecimal> values) {
            addCriterion("order_amt not in", values, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_amt between", value1, value2, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andOrderAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("order_amt not between", value1, value2, "orderAmt");
            return (Criteria) this;
        }

        public Criteria andPostFeeIsNull() {
            addCriterion("post_fee is null");
            return (Criteria) this;
        }

        public Criteria andPostFeeIsNotNull() {
            addCriterion("post_fee is not null");
            return (Criteria) this;
        }

        public Criteria andPostFeeEqualTo(BigDecimal value) {
            addCriterion("post_fee =", value, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeNotEqualTo(BigDecimal value) {
            addCriterion("post_fee <>", value, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeGreaterThan(BigDecimal value) {
            addCriterion("post_fee >", value, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("post_fee >=", value, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeLessThan(BigDecimal value) {
            addCriterion("post_fee <", value, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("post_fee <=", value, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeIn(List<BigDecimal> values) {
            addCriterion("post_fee in", values, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeNotIn(List<BigDecimal> values) {
            addCriterion("post_fee not in", values, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("post_fee between", value1, value2, "postFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("post_fee not between", value1, value2, "postFee");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNull() {
            addCriterion("payment is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNotNull() {
            addCriterion("payment is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentEqualTo(BigDecimal value) {
            addCriterion("payment =", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotEqualTo(BigDecimal value) {
            addCriterion("payment <>", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThan(BigDecimal value) {
            addCriterion("payment >", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("payment >=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThan(BigDecimal value) {
            addCriterion("payment <", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("payment <=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentIn(List<BigDecimal> values) {
            addCriterion("payment in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotIn(List<BigDecimal> values) {
            addCriterion("payment not in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("payment between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("payment not between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andItemCdIsNull() {
            addCriterion("item_cd is null");
            return (Criteria) this;
        }

        public Criteria andItemCdIsNotNull() {
            addCriterion("item_cd is not null");
            return (Criteria) this;
        }

        public Criteria andItemCdEqualTo(String value) {
            addCriterion("item_cd =", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotEqualTo(String value) {
            addCriterion("item_cd <>", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdGreaterThan(String value) {
            addCriterion("item_cd >", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdGreaterThanOrEqualTo(String value) {
            addCriterion("item_cd >=", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLessThan(String value) {
            addCriterion("item_cd <", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLessThanOrEqualTo(String value) {
            addCriterion("item_cd <=", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLike(String value) {
            addCriterion("item_cd like", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotLike(String value) {
            addCriterion("item_cd not like", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdIn(List<String> values) {
            addCriterion("item_cd in", values, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotIn(List<String> values) {
            addCriterion("item_cd not in", values, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdBetween(String value1, String value2) {
            addCriterion("item_cd between", value1, value2, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotBetween(String value1, String value2) {
            addCriterion("item_cd not between", value1, value2, "itemCd");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNull() {
            addCriterion("sku_cd is null");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNotNull() {
            addCriterion("sku_cd is not null");
            return (Criteria) this;
        }

        public Criteria andSkuCdEqualTo(String value) {
            addCriterion("sku_cd =", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotEqualTo(String value) {
            addCriterion("sku_cd <>", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThan(String value) {
            addCriterion("sku_cd >", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThanOrEqualTo(String value) {
            addCriterion("sku_cd >=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThan(String value) {
            addCriterion("sku_cd <", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThanOrEqualTo(String value) {
            addCriterion("sku_cd <=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLike(String value) {
            addCriterion("sku_cd like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotLike(String value) {
            addCriterion("sku_cd not like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdIn(List<String> values) {
            addCriterion("sku_cd in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotIn(List<String> values) {
            addCriterion("sku_cd not in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdBetween(String value1, String value2) {
            addCriterion("sku_cd between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotBetween(String value1, String value2) {
            addCriterion("sku_cd not between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andSubtotalIsNull() {
            addCriterion("subtotal is null");
            return (Criteria) this;
        }

        public Criteria andSubtotalIsNotNull() {
            addCriterion("subtotal is not null");
            return (Criteria) this;
        }

        public Criteria andSubtotalEqualTo(BigDecimal value) {
            addCriterion("subtotal =", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalNotEqualTo(BigDecimal value) {
            addCriterion("subtotal <>", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalGreaterThan(BigDecimal value) {
            addCriterion("subtotal >", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("subtotal >=", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalLessThan(BigDecimal value) {
            addCriterion("subtotal <", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("subtotal <=", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalIn(List<BigDecimal> values) {
            addCriterion("subtotal in", values, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalNotIn(List<BigDecimal> values) {
            addCriterion("subtotal not in", values, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("subtotal between", value1, value2, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("subtotal not between", value1, value2, "subtotal");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andBuyerNickIsNull() {
            addCriterion("buyer_nick is null");
            return (Criteria) this;
        }

        public Criteria andBuyerNickIsNotNull() {
            addCriterion("buyer_nick is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerNickEqualTo(String value) {
            addCriterion("buyer_nick =", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickNotEqualTo(String value) {
            addCriterion("buyer_nick <>", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickGreaterThan(String value) {
            addCriterion("buyer_nick >", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_nick >=", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickLessThan(String value) {
            addCriterion("buyer_nick <", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickLessThanOrEqualTo(String value) {
            addCriterion("buyer_nick <=", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickLike(String value) {
            addCriterion("buyer_nick like", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickNotLike(String value) {
            addCriterion("buyer_nick not like", value, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickIn(List<String> values) {
            addCriterion("buyer_nick in", values, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickNotIn(List<String> values) {
            addCriterion("buyer_nick not in", values, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickBetween(String value1, String value2) {
            addCriterion("buyer_nick between", value1, value2, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andBuyerNickNotBetween(String value1, String value2) {
            addCriterion("buyer_nick not between", value1, value2, "buyerNick");
            return (Criteria) this;
        }

        public Criteria andReceiverNameIsNull() {
            addCriterion("receiver_name is null");
            return (Criteria) this;
        }

        public Criteria andReceiverNameIsNotNull() {
            addCriterion("receiver_name is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverNameEqualTo(String value) {
            addCriterion("receiver_name =", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotEqualTo(String value) {
            addCriterion("receiver_name <>", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameGreaterThan(String value) {
            addCriterion("receiver_name >", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameGreaterThanOrEqualTo(String value) {
            addCriterion("receiver_name >=", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameLessThan(String value) {
            addCriterion("receiver_name <", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameLessThanOrEqualTo(String value) {
            addCriterion("receiver_name <=", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameLike(String value) {
            addCriterion("receiver_name like", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotLike(String value) {
            addCriterion("receiver_name not like", value, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameIn(List<String> values) {
            addCriterion("receiver_name in", values, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotIn(List<String> values) {
            addCriterion("receiver_name not in", values, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameBetween(String value1, String value2) {
            addCriterion("receiver_name between", value1, value2, "receiverName");
            return (Criteria) this;
        }

        public Criteria andReceiverNameNotBetween(String value1, String value2) {
            addCriterion("receiver_name not between", value1, value2, "receiverName");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeIsNull() {
            addCriterion("alipay_fee is null");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeIsNotNull() {
            addCriterion("alipay_fee is not null");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeEqualTo(BigDecimal value) {
            addCriterion("alipay_fee =", value, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeNotEqualTo(BigDecimal value) {
            addCriterion("alipay_fee <>", value, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeGreaterThan(BigDecimal value) {
            addCriterion("alipay_fee >", value, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("alipay_fee >=", value, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeLessThan(BigDecimal value) {
            addCriterion("alipay_fee <", value, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("alipay_fee <=", value, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeIn(List<BigDecimal> values) {
            addCriterion("alipay_fee in", values, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeNotIn(List<BigDecimal> values) {
            addCriterion("alipay_fee not in", values, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("alipay_fee between", value1, value2, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("alipay_fee not between", value1, value2, "alipayFee");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffIsNull() {
            addCriterion("alipay_fee_diff is null");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffIsNotNull() {
            addCriterion("alipay_fee_diff is not null");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffEqualTo(BigDecimal value) {
            addCriterion("alipay_fee_diff =", value, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffNotEqualTo(BigDecimal value) {
            addCriterion("alipay_fee_diff <>", value, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffGreaterThan(BigDecimal value) {
            addCriterion("alipay_fee_diff >", value, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("alipay_fee_diff >=", value, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffLessThan(BigDecimal value) {
            addCriterion("alipay_fee_diff <", value, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffLessThanOrEqualTo(BigDecimal value) {
            addCriterion("alipay_fee_diff <=", value, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffIn(List<BigDecimal> values) {
            addCriterion("alipay_fee_diff in", values, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffNotIn(List<BigDecimal> values) {
            addCriterion("alipay_fee_diff not in", values, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("alipay_fee_diff between", value1, value2, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andAlipayFeeDiffNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("alipay_fee_diff not between", value1, value2, "alipayFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPointFeeIsNull() {
            addCriterion("point_fee is null");
            return (Criteria) this;
        }

        public Criteria andPointFeeIsNotNull() {
            addCriterion("point_fee is not null");
            return (Criteria) this;
        }

        public Criteria andPointFeeEqualTo(BigDecimal value) {
            addCriterion("point_fee =", value, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeNotEqualTo(BigDecimal value) {
            addCriterion("point_fee <>", value, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeGreaterThan(BigDecimal value) {
            addCriterion("point_fee >", value, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("point_fee >=", value, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeLessThan(BigDecimal value) {
            addCriterion("point_fee <", value, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("point_fee <=", value, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeIn(List<BigDecimal> values) {
            addCriterion("point_fee in", values, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeNotIn(List<BigDecimal> values) {
            addCriterion("point_fee not in", values, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("point_fee between", value1, value2, "pointFee");
            return (Criteria) this;
        }

        public Criteria andPointFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("point_fee not between", value1, value2, "pointFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeIsNull() {
            addCriterion("tb_commission_fee is null");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeIsNotNull() {
            addCriterion("tb_commission_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeEqualTo(BigDecimal value) {
            addCriterion("tb_commission_fee =", value, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeNotEqualTo(BigDecimal value) {
            addCriterion("tb_commission_fee <>", value, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeGreaterThan(BigDecimal value) {
            addCriterion("tb_commission_fee >", value, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tb_commission_fee >=", value, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeLessThan(BigDecimal value) {
            addCriterion("tb_commission_fee <", value, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tb_commission_fee <=", value, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeIn(List<BigDecimal> values) {
            addCriterion("tb_commission_fee in", values, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeNotIn(List<BigDecimal> values) {
            addCriterion("tb_commission_fee not in", values, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tb_commission_fee between", value1, value2, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbCommissionFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tb_commission_fee not between", value1, value2, "tbCommissionFee");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeIsNull() {
            addCriterion("alipay_time is null");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeIsNotNull() {
            addCriterion("alipay_time is not null");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeEqualTo(Date value) {
            addCriterion("alipay_time =", value, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeNotEqualTo(Date value) {
            addCriterion("alipay_time <>", value, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeGreaterThan(Date value) {
            addCriterion("alipay_time >", value, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("alipay_time >=", value, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeLessThan(Date value) {
            addCriterion("alipay_time <", value, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeLessThanOrEqualTo(Date value) {
            addCriterion("alipay_time <=", value, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeIn(List<Date> values) {
            addCriterion("alipay_time in", values, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeNotIn(List<Date> values) {
            addCriterion("alipay_time not in", values, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeBetween(Date value1, Date value2) {
            addCriterion("alipay_time between", value1, value2, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andAlipayTimeNotBetween(Date value1, Date value2) {
            addCriterion("alipay_time not between", value1, value2, "alipayTime");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeIsNull() {
            addCriterion("tbke_commission_fee is null");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeIsNotNull() {
            addCriterion("tbke_commission_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeEqualTo(BigDecimal value) {
            addCriterion("tbke_commission_fee =", value, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeNotEqualTo(BigDecimal value) {
            addCriterion("tbke_commission_fee <>", value, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeGreaterThan(BigDecimal value) {
            addCriterion("tbke_commission_fee >", value, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tbke_commission_fee >=", value, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeLessThan(BigDecimal value) {
            addCriterion("tbke_commission_fee <", value, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tbke_commission_fee <=", value, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeIn(List<BigDecimal> values) {
            addCriterion("tbke_commission_fee in", values, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeNotIn(List<BigDecimal> values) {
            addCriterion("tbke_commission_fee not in", values, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tbke_commission_fee between", value1, value2, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andTbkeCommissionFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tbke_commission_fee not between", value1, value2, "tbkeCommissionFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeIsNull() {
            addCriterion("wms_post_fee is null");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeIsNotNull() {
            addCriterion("wms_post_fee is not null");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeEqualTo(BigDecimal value) {
            addCriterion("wms_post_fee =", value, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeNotEqualTo(BigDecimal value) {
            addCriterion("wms_post_fee <>", value, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeGreaterThan(BigDecimal value) {
            addCriterion("wms_post_fee >", value, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wms_post_fee >=", value, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeLessThan(BigDecimal value) {
            addCriterion("wms_post_fee <", value, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wms_post_fee <=", value, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeIn(List<BigDecimal> values) {
            addCriterion("wms_post_fee in", values, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeNotIn(List<BigDecimal> values) {
            addCriterion("wms_post_fee not in", values, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wms_post_fee between", value1, value2, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andWmsPostFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wms_post_fee not between", value1, value2, "wmsPostFee");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffIsNull() {
            addCriterion("post_fee_diff is null");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffIsNotNull() {
            addCriterion("post_fee_diff is not null");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffEqualTo(BigDecimal value) {
            addCriterion("post_fee_diff =", value, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffNotEqualTo(BigDecimal value) {
            addCriterion("post_fee_diff <>", value, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffGreaterThan(BigDecimal value) {
            addCriterion("post_fee_diff >", value, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("post_fee_diff >=", value, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffLessThan(BigDecimal value) {
            addCriterion("post_fee_diff <", value, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffLessThanOrEqualTo(BigDecimal value) {
            addCriterion("post_fee_diff <=", value, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffIn(List<BigDecimal> values) {
            addCriterion("post_fee_diff in", values, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffNotIn(List<BigDecimal> values) {
            addCriterion("post_fee_diff not in", values, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("post_fee_diff between", value1, value2, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andPostFeeDiffNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("post_fee_diff not between", value1, value2, "postFeeDiff");
            return (Criteria) this;
        }

        public Criteria andCostPriceIsNull() {
            addCriterion("cost_price is null");
            return (Criteria) this;
        }

        public Criteria andCostPriceIsNotNull() {
            addCriterion("cost_price is not null");
            return (Criteria) this;
        }

        public Criteria andCostPriceEqualTo(BigDecimal value) {
            addCriterion("cost_price =", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceNotEqualTo(BigDecimal value) {
            addCriterion("cost_price <>", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceGreaterThan(BigDecimal value) {
            addCriterion("cost_price >", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_price >=", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceLessThan(BigDecimal value) {
            addCriterion("cost_price <", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_price <=", value, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceIn(List<BigDecimal> values) {
            addCriterion("cost_price in", values, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceNotIn(List<BigDecimal> values) {
            addCriterion("cost_price not in", values, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_price between", value1, value2, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_price not between", value1, value2, "costPrice");
            return (Criteria) this;
        }

        public Criteria andCostAmtIsNull() {
            addCriterion("cost_amt is null");
            return (Criteria) this;
        }

        public Criteria andCostAmtIsNotNull() {
            addCriterion("cost_amt is not null");
            return (Criteria) this;
        }

        public Criteria andCostAmtEqualTo(BigDecimal value) {
            addCriterion("cost_amt =", value, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtNotEqualTo(BigDecimal value) {
            addCriterion("cost_amt <>", value, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtGreaterThan(BigDecimal value) {
            addCriterion("cost_amt >", value, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_amt >=", value, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtLessThan(BigDecimal value) {
            addCriterion("cost_amt <", value, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_amt <=", value, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtIn(List<BigDecimal> values) {
            addCriterion("cost_amt in", values, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtNotIn(List<BigDecimal> values) {
            addCriterion("cost_amt not in", values, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_amt between", value1, value2, "costAmt");
            return (Criteria) this;
        }

        public Criteria andCostAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_amt not between", value1, value2, "costAmt");
            return (Criteria) this;
        }

        public Criteria andGrossMarginIsNull() {
            addCriterion("gross_margin is null");
            return (Criteria) this;
        }

        public Criteria andGrossMarginIsNotNull() {
            addCriterion("gross_margin is not null");
            return (Criteria) this;
        }

        public Criteria andGrossMarginEqualTo(BigDecimal value) {
            addCriterion("gross_margin =", value, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginNotEqualTo(BigDecimal value) {
            addCriterion("gross_margin <>", value, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginGreaterThan(BigDecimal value) {
            addCriterion("gross_margin >", value, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("gross_margin >=", value, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginLessThan(BigDecimal value) {
            addCriterion("gross_margin <", value, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginLessThanOrEqualTo(BigDecimal value) {
            addCriterion("gross_margin <=", value, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginIn(List<BigDecimal> values) {
            addCriterion("gross_margin in", values, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginNotIn(List<BigDecimal> values) {
            addCriterion("gross_margin not in", values, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("gross_margin between", value1, value2, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andGrossMarginNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("gross_margin not between", value1, value2, "grossMargin");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("tid is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("tid is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(String value) {
            addCriterion("tid =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(String value) {
            addCriterion("tid <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(String value) {
            addCriterion("tid >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(String value) {
            addCriterion("tid >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(String value) {
            addCriterion("tid <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(String value) {
            addCriterion("tid <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLike(String value) {
            addCriterion("tid like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotLike(String value) {
            addCriterion("tid not like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<String> values) {
            addCriterion("tid in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<String> values) {
            addCriterion("tid not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(String value1, String value2) {
            addCriterion("tid between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(String value1, String value2) {
            addCriterion("tid not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeIsNull() {
            addCriterion("credit_card_fee is null");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeIsNotNull() {
            addCriterion("credit_card_fee is not null");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeEqualTo(BigDecimal value) {
            addCriterion("credit_card_fee =", value, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeNotEqualTo(BigDecimal value) {
            addCriterion("credit_card_fee <>", value, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeGreaterThan(BigDecimal value) {
            addCriterion("credit_card_fee >", value, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("credit_card_fee >=", value, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeLessThan(BigDecimal value) {
            addCriterion("credit_card_fee <", value, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("credit_card_fee <=", value, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeIn(List<BigDecimal> values) {
            addCriterion("credit_card_fee in", values, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeNotIn(List<BigDecimal> values) {
            addCriterion("credit_card_fee not in", values, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("credit_card_fee between", value1, value2, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andCreditCardFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("credit_card_fee not between", value1, value2, "creditCardFee");
            return (Criteria) this;
        }

        public Criteria andOidIsNull() {
            addCriterion("oid is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oid is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(String value) {
            addCriterion("oid =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(String value) {
            addCriterion("oid <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(String value) {
            addCriterion("oid >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(String value) {
            addCriterion("oid >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(String value) {
            addCriterion("oid <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(String value) {
            addCriterion("oid <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLike(String value) {
            addCriterion("oid like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotLike(String value) {
            addCriterion("oid not like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<String> values) {
            addCriterion("oid in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<String> values) {
            addCriterion("oid not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(String value1, String value2) {
            addCriterion("oid between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(String value1, String value2) {
            addCriterion("oid not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundIsNull() {
            addCriterion("current_month_refund is null");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundIsNotNull() {
            addCriterion("current_month_refund is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundEqualTo(BigDecimal value) {
            addCriterion("current_month_refund =", value, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundNotEqualTo(BigDecimal value) {
            addCriterion("current_month_refund <>", value, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundGreaterThan(BigDecimal value) {
            addCriterion("current_month_refund >", value, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_month_refund >=", value, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundLessThan(BigDecimal value) {
            addCriterion("current_month_refund <", value, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_month_refund <=", value, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundIn(List<BigDecimal> values) {
            addCriterion("current_month_refund in", values, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundNotIn(List<BigDecimal> values) {
            addCriterion("current_month_refund not in", values, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_month_refund between", value1, value2, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andCurrentMonthRefundNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_month_refund not between", value1, value2, "currentMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundIsNull() {
            addCriterion("other_month_refund is null");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundIsNotNull() {
            addCriterion("other_month_refund is not null");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundEqualTo(BigDecimal value) {
            addCriterion("other_month_refund =", value, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundNotEqualTo(BigDecimal value) {
            addCriterion("other_month_refund <>", value, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundGreaterThan(BigDecimal value) {
            addCriterion("other_month_refund >", value, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("other_month_refund >=", value, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundLessThan(BigDecimal value) {
            addCriterion("other_month_refund <", value, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundLessThanOrEqualTo(BigDecimal value) {
            addCriterion("other_month_refund <=", value, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundIn(List<BigDecimal> values) {
            addCriterion("other_month_refund in", values, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundNotIn(List<BigDecimal> values) {
            addCriterion("other_month_refund not in", values, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_month_refund between", value1, value2, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOtherMonthRefundNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_month_refund not between", value1, value2, "otherMonthRefund");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andPostNoIsNull() {
            addCriterion("post_no is null");
            return (Criteria) this;
        }

        public Criteria andPostNoIsNotNull() {
            addCriterion("post_no is not null");
            return (Criteria) this;
        }

        public Criteria andPostNoEqualTo(String value) {
            addCriterion("post_no =", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotEqualTo(String value) {
            addCriterion("post_no <>", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoGreaterThan(String value) {
            addCriterion("post_no >", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoGreaterThanOrEqualTo(String value) {
            addCriterion("post_no >=", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoLessThan(String value) {
            addCriterion("post_no <", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoLessThanOrEqualTo(String value) {
            addCriterion("post_no <=", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoLike(String value) {
            addCriterion("post_no like", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotLike(String value) {
            addCriterion("post_no not like", value, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoIn(List<String> values) {
            addCriterion("post_no in", values, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotIn(List<String> values) {
            addCriterion("post_no not in", values, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoBetween(String value1, String value2) {
            addCriterion("post_no between", value1, value2, "postNo");
            return (Criteria) this;
        }

        public Criteria andPostNoNotBetween(String value1, String value2) {
            addCriterion("post_no not between", value1, value2, "postNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table taobao_account_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table taobao_account_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}