package com.sunmw.paipai.dao;

import com.sunmw.paipai.domain.PpStore;
import com.sunmw.paipai.domain.PpStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PpStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int countByExample(PpStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int deleteByExample(PpStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int insert(PpStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int insertSelective(PpStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    List<PpStore> selectByExample(PpStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    PpStore selectByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PpStore record, @Param("example") PpStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PpStore record, @Param("example") PpStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PpStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pp_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PpStore record);
}